### ISSUE TITLE
Keep older versions of debian packages in the repository

### ISSUE THREAD

**Issue by Congelli501** [nodesource/distributions#1021]
The latest node release contains an important regression, breaking a lot of application (https://github.com/nodejs/node/issues/32105).
As the nodesource repository only contains the latest version of node, it is not possible to install an older version of node in the meantime.

This is especially needed for docker images built from the ubuntu / debian base image, in which we can't install anything but the lastest version of each node major release.

```
 % apt-cache madison nodejs 
    nodejs | 13.10.1-1nodesource1 | https://deb.nodesource.com/node_13.x eoan/main amd64 Packages
    nodejs | 10.15.2~dfsg-2ubuntu1 | http://fr.archive.ubuntu.com/ubuntu eoan/universe amd64 Packages
```

For example, the kubernetes debian repo contains a lot of different version of the same package, allowing downgrade if need be:
```
 % apt-cache madison kubectl
   kubectl |  1.17.3-00 | https://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
   kubectl |  1.17.2-00 | https://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
   kubectl |  1.17.1-00 | https://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
   kubectl |  1.17.0-00 | https://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
   kubectl |  1.16.7-00 | https://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
   kubectl |  1.16.6-00 | https://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
...
```

Keeping versions for a month would be very helpful in those situation.

**Comment by zerodeux** [comment]
I second that.

The good news is that the repository is already holding the previous versions : https://deb.nodesource.com/node_12.x/pool/main/n/nodejs/

What is missing is only the way the Release file is built in the APT repo, it should mention all versions instead of only the latest one, and APT would automatically discover them. It should be a one line conf change in the repo builder.

That change would be backwards compatible : it will not break the existing behaviour for current users, they will always get the latest minor release from their APT source.

But for those who would want to pin down a specific version, it would be as simple as :

    apt-get install nodejs=12.16.3-1nodesource1

**Comment by zerodeux** [comment]
@igsu any idea who to assign this ? Thanks !

**Comment by igsu** [comment]
@zerodeux as stated in the FAQ: https://github.com/nodesource/distributions/issues/33#issuecomment-169345680 this has been considered by us, we will evaluate options to achieve a solution.

**Comment by dylan-tock** [comment]
> @zerodeux as stated in the FAQ: [#33 (comment)](https://github.com/nodesource/distributions/issues/33#issuecomment-169345680) this has been considered by us, we will evaluate options to achieve a solution.

@igsu Given Issue #33 has been closed without a fix (by you, in fact) Jan this year, is there any progress on implementing a permanent fix?
