### ISSUE TITLE
most recent few 10.x versions not available on https://rpm.nodesource.com/pub_10.x/el/6/x86_64/

### ISSUE THREAD

**Issue by rhbecker** [nodesource/distributions#1080]
Is it on purpose that the most recent `10.x` release on https://rpm.nodesource.com/pub_10.x/el/6/x86_64/ is `10.19.0`?

I'm asking because I was expecting to also find [subsequent release versions](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md) `10.21.0`, `10.20.1`, and `10.20.0` (I primarily care about `10.21.0`).

**Comment by igsu** [comment]
Hi @rhbecker, yes it is on purpose. Node.js 12 support for RHEL starts from version 7, we stopped building Node.js 12 for RHEL because it requires dependencies that are not possible to install or resolve in RHEL 6 to support Node.js 12:

https://github.com/nodejs/build/issues/1995
https://github.com/nodejs/node/blob/v12.x/BUILDING.md#supported-platforms

RHEL version 6 was removed on `10.19.0` to avoid future dependency problems.
Please consider that it will reach ELP in November 2020.

**Comment by rhbecker** [comment]
@igsu: I was asking a bout more recent 10.x versions ... not 12.x. I assumed you'd continue including 10.x patches.

Are you suggesting that `10.21.0`, etc. would have dependency issues on RHEL 6? Or just that you decided `10.19.0` was the last version of 10.x that you were going to support?
