### ISSUE TITLE
what about raspberry pi os desktop 64x86?

### ISSUE THREAD

**Issue by jt3k** [nodesource/distributions#1144]
my computer is Intel-atom+nvidia_ION.
i installed raspberry-pi-desktop using this link https://www.raspberrypi.org/software/raspberry-pi-desktop/

i tried to install node 15 
and get this message:
```
pi@raspberry:~ $ curl -sL https://rpm.nodesource.com/setup_15.x | sudo bash -

## Installing the NodeSource Node.js 15.x repo...


## Inspecting system...


## You don't appear to be running an Enterprise Linux based system,
please contact NodeSource at https://github.com/nodesource/distributions/issues
if you think this is incorrect or would like your distribution to be considered
for support.
```

I also tried the manual instalation, and see only node v10 in my package manager

system-Info
```
pi@raspberry:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
pi@raspberry:~ $ cat /etc/debian_version 
10.7
pi@raspberry:~ $ uname -a
Linux raspberry 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

```

**Comment by igsu** [comment]
Hey @jt3k, Debian `buster` is currently supported. The issue here is that you are trying to use the wrong installation script (Debian is not an Enterprise Linux based distribution).

Please follow the instructions [here](https://github.com/nodesource/distributions#debian-and-ubuntu-based-distributions).
