### ISSUE TITLE
NodeJS installation failed in buster 10

### ISSUE THREAD

**Issue by Manishcimcon** [nodesource/distributions#1209]
We have tried to install nodeJS on Debian buster 10 kernel 4.9. as followed below step.

# Using Debian, as root
curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
apt-get install -y nodejs

and we got the below error
root@tsimx6:/home/nodejs# curl -fskSL https://deb.nodesource.com/setup_16.x | bash -

## Populating apt-get cache...

+ apt-get update
Hit:1 http://deb.debian.org/debian buster InRelease
Reading package lists... Done

## Confirming "buster" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists/buster/Release'

## Your distribution, identified as "buster", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by blec123** [comment]
Did you find a solution yet? 
I got the same problem with the lts version. 

 > [10/14] RUN curl -fsSL https://deb.nodesource.com/setup_lts.x -k | bash -:
#14 1.620
#14 1.620 ## Installing the NodeSource Node.js 14.x repo...
#14 1.620
#14 1.623
#14 1.623 ## Populating apt-get cache...
#14 1.623
#14 1.623 + apt-get update
#14 1.708 Get:1 http://security.debian.org/debian-security stable/updates InRelease [65.4 kB]
#14 1.731 Get:2 http://deb.debian.org/debian stable InRelease [121 kB]
#14 1.914 Get:3 http://deb.debian.org/debian stable-updates InRelease [51.9 kB]
#14 1.958 Get:4 http://security.debian.org/debian-security stable/updates/main amd64 Packages [290 kB]
#14 3.069 Get:5 http://deb.debian.org/debian stable/main amd64 Packages [7907 kB]
#14 6.635 Get:6 http://deb.debian.org/debian stable-updates/main amd64 Packages [10.9 kB]
#14 7.351 Fetched 8447 kB in 6s (1481 kB/s)
#14 7.351 Reading package lists...
#14 7.819
#14 7.819 ## Confirming "buster" is supported...
#14 7.819
#14 7.819 + curl -sLf -o /dev/null 'https://deb.nodesource.com/node_14.x/dists/buster/Release'
#14 7.918
#14 7.918 ## Your distribution, identified as "buster", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by nigeldunn-pexa** [comment]
This is also failing for me. Here is the example Dockerfile to recreate the issue...

`
FROM debian:buster as runtime
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y curl && \
    curl -kfsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs && \
    apt-get -y clean all
`

Results in the following...

`
 > [runtime 3/5] RUN apt-get update &&     apt-get upgrade -y &&     apt-get install -y curl &&     curl -kfsSL https://deb.nodesource.com/setup_lts.x | bash - &&     apt-get install -y nodejs &&     apt-get -y clean all:
#7 1.292 Get:1 http://deb.debian.org/debian buster InRelease [121 kB]
#7 1.371 Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
#7 1.385 Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
#7 1.953 Get:4 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
#7 3.119 Get:5 http://security.debian.org/debian-security buster/updates/main amd64 Packages [292 kB]
#7 4.471 Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [10.9 kB]
#7 8.371 Fetched 8449 kB in 7s (1131 kB/s)
#7 8.371 Reading package lists...
#7 11.47 Reading package lists...
#7 16.49 Building dependency tree...
#7 17.43 Reading state information...
#7 17.56 Calculating upgrade...
#7 18.21 The following packages will be upgraded:
#7 18.21   liblz4-1
#7 18.83 1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
#7 18.83 Need to get 53.3 kB of archives.
#7 18.83 After this operation, 0 B of additional disk space will be used.
#7 18.83 Get:1 http://security.debian.org/debian-security buster/updates/main amd64 liblz4-1 amd64 1.8.3-1+deb10u1 [53.3 kB]
#7 20.38 debconf: delaying package configuration, since apt-utils is not installed
#7 20.50 Fetched 53.3 kB in 1s (86.0 kB/s)
(Reading database ... 6677 files and directories currently installed.)
#7 20.79 Preparing to unpack .../liblz4-1_1.8.3-1+deb10u1_amd64.deb ...
#7 20.83 Unpacking liblz4-1:amd64 (1.8.3-1+deb10u1) over (1.8.3-1) ...
#7 21.35 Setting up liblz4-1:amd64 (1.8.3-1+deb10u1) ...
#7 21.44 Processing triggers for libc-bin (2.28-10) ...
#7 21.74 Reading package lists...
#7 24.91 Building dependency tree...
#7 25.59 Reading state information...
#7 26.39 The following additional packages will be installed:
#7 26.39   ca-certificates krb5-locales libcurl4 libgssapi-krb5-2 libk5crypto3
#7 26.39   libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common
#7 26.39   libnghttp2-14 libpsl5 librtmp1 libsasl2-2 libsasl2-modules
#7 26.39   libsasl2-modules-db libssh2-1 libssl1.1 openssl publicsuffix
#7 26.40 Suggested packages:
#7 26.40   krb5-doc krb5-user libsasl2-modules-gssapi-mit
#7 26.40   | libsasl2-modules-gssapi-heimdal libsasl2-modules-ldap libsasl2-modules-otp
#7 26.40   libsasl2-modules-sql
#7 27.02 The following NEW packages will be installed:
#7 27.03   ca-certificates curl krb5-locales libcurl4 libgssapi-krb5-2 libk5crypto3
#7 27.03   libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2 libldap-common
#7 27.03   libnghttp2-14 libpsl5 librtmp1 libsasl2-2 libsasl2-modules
#7 27.03   libsasl2-modules-db libssh2-1 libssl1.1 openssl publicsuffix
#7 27.42 0 upgraded, 21 newly installed, 0 to remove and 0 not upgraded.
#7 27.42 Need to get 5020 kB of archives.
#7 27.42 After this operation, 11.9 MB of additional disk space will be used.
#7 27.42 Get:1 http://deb.debian.org/debian buster/main amd64 krb5-locales all 1.17-3+deb10u1 [95.4 kB]
#7 27.42 Get:2 http://security.debian.org/debian-security buster/updates/main amd64 libssl1.1 amd64 1.1.1d-0+deb10u6 [1539 kB]
#7 27.75 Get:3 http://deb.debian.org/debian buster/main amd64 ca-certificates all 20200601~deb10u2 [166 kB]
#7 27.75 Get:4 http://deb.debian.org/debian buster/main amd64 libkeyutils1 amd64 1.6-6 [15.0 kB]
#7 27.75 Get:5 http://deb.debian.org/debian buster/main amd64 libkrb5support0 amd64 1.17-3+deb10u1 [65.8 kB]
#7 27.75 Get:6 http://deb.debian.org/debian buster/main amd64 libk5crypto3 amd64 1.17-3+deb10u1 [122 kB]
#7 27.89 Get:7 http://deb.debian.org/debian buster/main amd64 libkrb5-3 amd64 1.17-3+deb10u1 [369 kB]
#7 27.98 Get:8 http://deb.debian.org/debian buster/main amd64 libgssapi-krb5-2 amd64 1.17-3+deb10u1 [158 kB]
#7 28.02 Get:9 http://deb.debian.org/debian buster/main amd64 libsasl2-modules-db amd64 2.1.27+dfsg-1+deb10u1 [69.1 kB]
#7 28.02 Get:10 http://deb.debian.org/debian buster/main amd64 libsasl2-2 amd64 2.1.27+dfsg-1+deb10u1 [106 kB]
#7 28.07 Get:11 http://deb.debian.org/debian buster/main amd64 libldap-common all 2.4.47+dfsg-3+deb10u6 [90.0 kB]
#7 28.14 Get:12 http://deb.debian.org/debian buster/main amd64 libldap-2.4-2 amd64 2.4.47+dfsg-3+deb10u6 [224 kB]
#7 28.14 Get:13 http://security.debian.org/debian-security buster/updates/main amd64 openssl amd64 1.1.1d-0+deb10u6 [844 kB]
#7 28.18 Get:14 http://deb.debian.org/debian buster/main amd64 libnghttp2-14 amd64 1.36.0-2+deb10u1 [85.0 kB]
#7 28.18 Get:15 http://deb.debian.org/debian buster/main amd64 libpsl5 amd64 0.20.2-2 [53.7 kB]
#7 28.21 Get:16 http://deb.debian.org/debian buster/main amd64 librtmp1 amd64 2.4+20151223.gitfa8646d.1-2 [60.5 kB]
#7 28.23 Get:17 http://deb.debian.org/debian buster/main amd64 libssh2-1 amd64 1.8.0-2.1 [140 kB]
#7 28.25 Get:18 http://deb.debian.org/debian buster/main amd64 libsasl2-modules amd64 2.1.27+dfsg-1+deb10u1 [104 kB]
#7 28.26 Get:19 http://deb.debian.org/debian buster/main amd64 publicsuffix all 20190415.1030-1 [116 kB]
#7 28.44 Get:20 http://security.debian.org/debian-security buster/updates/main amd64 libcurl4 amd64 7.64.0-4+deb10u2 [332 kB]
#7 28.47 Get:21 http://security.debian.org/debian-security buster/updates/main amd64 curl amd64 7.64.0-4+deb10u2 [265 kB]
#7 29.46 debconf: delaying package configuration, since apt-utils is not installed
#7 29.63 Fetched 5020 kB in 1s (3479 kB/s)
#7 29.81 Selecting previously unselected package libssl1.1:amd64.
(Reading database ... 6677 files and directories currently installed.)
#7 29.82 Preparing to unpack .../00-libssl1.1_1.1.1d-0+deb10u6_amd64.deb ...
#7 29.84 Unpacking libssl1.1:amd64 (1.1.1d-0+deb10u6) ...
#7 30.43 Selecting previously unselected package krb5-locales.
#7 30.44 Preparing to unpack .../01-krb5-locales_1.17-3+deb10u1_all.deb ...
#7 30.45 Unpacking krb5-locales (1.17-3+deb10u1) ...
#7 30.70 Selecting previously unselected package openssl.
#7 30.70 Preparing to unpack .../02-openssl_1.1.1d-0+deb10u6_amd64.deb ...
#7 30.70 Unpacking openssl (1.1.1d-0+deb10u6) ...
#7 30.99 Selecting previously unselected package ca-certificates.
#7 30.99 Preparing to unpack .../03-ca-certificates_20200601~deb10u2_all.deb ...
#7 31.00 Unpacking ca-certificates (20200601~deb10u2) ...
#7 31.19 Selecting previously unselected package libkeyutils1:amd64.
#7 31.19 Preparing to unpack .../04-libkeyutils1_1.6-6_amd64.deb ...
#7 31.20 Unpacking libkeyutils1:amd64 (1.6-6) ...
#7 31.33 Selecting previously unselected package libkrb5support0:amd64.
#7 31.33 Preparing to unpack .../05-libkrb5support0_1.17-3+deb10u1_amd64.deb ...
#7 31.34 Unpacking libkrb5support0:amd64 (1.17-3+deb10u1) ...
#7 31.43 Selecting previously unselected package libk5crypto3:amd64.
#7 31.43 Preparing to unpack .../06-libk5crypto3_1.17-3+deb10u1_amd64.deb ...
#7 31.44 Unpacking libk5crypto3:amd64 (1.17-3+deb10u1) ...
#7 31.56 Selecting previously unselected package libkrb5-3:amd64.
#7 31.56 Preparing to unpack .../07-libkrb5-3_1.17-3+deb10u1_amd64.deb ...
#7 31.57 Unpacking libkrb5-3:amd64 (1.17-3+deb10u1) ...
#7 31.80 Selecting previously unselected package libgssapi-krb5-2:amd64.
#7 31.80 Preparing to unpack .../08-libgssapi-krb5-2_1.17-3+deb10u1_amd64.deb ...
#7 31.81 Unpacking libgssapi-krb5-2:amd64 (1.17-3+deb10u1) ...
#7 31.90 Selecting previously unselected package libsasl2-modules-db:amd64.
#7 31.90 Preparing to unpack .../09-libsasl2-modules-db_2.1.27+dfsg-1+deb10u1_amd64.deb ...
#7 31.91 Unpacking libsasl2-modules-db:amd64 (2.1.27+dfsg-1+deb10u1) ...
#7 32.32 Selecting previously unselected package libsasl2-2:amd64.
#7 32.32 Preparing to unpack .../10-libsasl2-2_2.1.27+dfsg-1+deb10u1_amd64.deb ...
#7 32.34 Unpacking libsasl2-2:amd64 (2.1.27+dfsg-1+deb10u1) ...
#7 32.50 Selecting previously unselected package libldap-common.
#7 32.50 Preparing to unpack .../11-libldap-common_2.4.47+dfsg-3+deb10u6_all.deb ...
#7 32.51 Unpacking libldap-common (2.4.47+dfsg-3+deb10u6) ...
#7 32.69 Selecting previously unselected package libldap-2.4-2:amd64.
#7 32.69 Preparing to unpack .../12-libldap-2.4-2_2.4.47+dfsg-3+deb10u6_amd64.deb ...
#7 32.70 Unpacking libldap-2.4-2:amd64 (2.4.47+dfsg-3+deb10u6) ...
#7 32.97 Selecting previously unselected package libnghttp2-14:amd64.
#7 32.97 Preparing to unpack .../13-libnghttp2-14_1.36.0-2+deb10u1_amd64.deb ...
#7 32.98 Unpacking libnghttp2-14:amd64 (1.36.0-2+deb10u1) ...
#7 33.10 Selecting previously unselected package libpsl5:amd64.
#7 33.10 Preparing to unpack .../14-libpsl5_0.20.2-2_amd64.deb ...
#7 33.11 Unpacking libpsl5:amd64 (0.20.2-2) ...
#7 33.26 Selecting previously unselected package librtmp1:amd64.
#7 33.26 Preparing to unpack .../15-librtmp1_2.4+20151223.gitfa8646d.1-2_amd64.deb ...
#7 33.27 Unpacking librtmp1:amd64 (2.4+20151223.gitfa8646d.1-2) ...
#7 33.40 Selecting previously unselected package libssh2-1:amd64.
#7 33.41 Preparing to unpack .../16-libssh2-1_1.8.0-2.1_amd64.deb ...
#7 33.42 Unpacking libssh2-1:amd64 (1.8.0-2.1) ...
#7 33.54 Selecting previously unselected package libcurl4:amd64.
#7 33.55 Preparing to unpack .../17-libcurl4_7.64.0-4+deb10u2_amd64.deb ...
#7 33.56 Unpacking libcurl4:amd64 (7.64.0-4+deb10u2) ...
#7 33.72 Selecting previously unselected package curl.
#7 33.72 Preparing to unpack .../18-curl_7.64.0-4+deb10u2_amd64.deb ...
#7 33.73 Unpacking curl (7.64.0-4+deb10u2) ...
#7 33.88 Selecting previously unselected package libsasl2-modules:amd64.
#7 33.88 Preparing to unpack .../19-libsasl2-modules_2.1.27+dfsg-1+deb10u1_amd64.deb ...
#7 33.89 Unpacking libsasl2-modules:amd64 (2.1.27+dfsg-1+deb10u1) ...
#7 34.02 Selecting previously unselected package publicsuffix.
#7 34.02 Preparing to unpack .../20-publicsuffix_20190415.1030-1_all.deb ...
#7 34.02 Unpacking publicsuffix (20190415.1030-1) ...
#7 34.16 Setting up libkeyutils1:amd64 (1.6-6) ...
#7 34.17 Setting up libpsl5:amd64 (0.20.2-2) ...
#7 34.20 Setting up libssl1.1:amd64 (1.1.1d-0+deb10u6) ...
#7 34.57 debconf: unable to initialize frontend: Dialog
#7 34.57 debconf: (TERM is not set, so the dialog frontend is not usable.)
#7 34.57 debconf: falling back to frontend: Readline
#7 34.58 debconf: unable to initialize frontend: Readline
#7 34.58 debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
#7 34.58 debconf: falling back to frontend: Teletype
#7 34.78 Setting up libsasl2-modules:amd64 (2.1.27+dfsg-1+deb10u1) ...
#7 34.83 Setting up libnghttp2-14:amd64 (1.36.0-2+deb10u1) ...
#7 34.86 Setting up krb5-locales (1.17-3+deb10u1) ...
#7 34.89 Setting up libldap-common (2.4.47+dfsg-3+deb10u6) ...
#7 34.92 Setting up libkrb5support0:amd64 (1.17-3+deb10u1) ...
#7 34.95 Setting up libsasl2-modules-db:amd64 (2.1.27+dfsg-1+deb10u1) ...
#7 34.97 Setting up librtmp1:amd64 (2.4+20151223.gitfa8646d.1-2) ...
#7 34.99 Setting up libk5crypto3:amd64 (1.17-3+deb10u1) ...
#7 35.03 Setting up libsasl2-2:amd64 (2.1.27+dfsg-1+deb10u1) ...
#7 35.05 Setting up libssh2-1:amd64 (1.8.0-2.1) ...
#7 35.09 Setting up libkrb5-3:amd64 (1.17-3+deb10u1) ...
#7 35.12 Setting up openssl (1.1.1d-0+deb10u6) ...
#7 35.15 Setting up publicsuffix (20190415.1030-1) ...
#7 35.17 Setting up libldap-2.4-2:amd64 (2.4.47+dfsg-3+deb10u6) ...
#7 35.19 Setting up ca-certificates (20200601~deb10u2) ...
#7 35.45 debconf: unable to initialize frontend: Dialog
#7 35.45 debconf: (TERM is not set, so the dialog frontend is not usable.)
#7 35.45 debconf: falling back to frontend: Readline
#7 35.45 debconf: unable to initialize frontend: Readline
#7 35.45 debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
#7 35.45 debconf: falling back to frontend: Teletype
#7 37.54 Updating certificates in /etc/ssl/certs...
#7 41.36 137 added, 0 removed; done.
#7 41.58 Setting up libgssapi-krb5-2:amd64 (1.17-3+deb10u1) ...
#7 41.62 Setting up libcurl4:amd64 (7.64.0-4+deb10u2) ...
#7 41.66 Setting up curl (7.64.0-4+deb10u2) ...
#7 41.69 Processing triggers for libc-bin (2.28-10) ...
#7 41.77 Processing triggers for ca-certificates (20200601~deb10u2) ...
#7 41.81 Updating certificates in /etc/ssl/certs...
#7 47.29 0 added, 0 removed; done.
#7 47.29 Running hooks in /etc/ca-certificates/update.d...
#7 47.31 done.
#7 47.65
#7 47.65 ## Installing the NodeSource Node.js 14.x repo...
#7 47.65
#7 47.66
#7 47.66 ## Populating apt-get cache...
#7 47.66
#7 47.66 + apt-get update
#7 47.94 Hit:1 http://security.debian.org/debian-security buster/updates InRelease
#7 47.94 Hit:2 http://deb.debian.org/debian buster InRelease
#7 47.97 Hit:3 http://deb.debian.org/debian buster-updates InRelease
#7 49.58 Reading package lists...
#7 52.44
#7 52.44 ## Installing packages required for setup: lsb-release gnupg...
#7 52.44
#7 52.44 + apt-get install -y lsb-release gnupg > /dev/null 2>&1
#7 75.28
#7 75.28 ## Confirming "buster" is supported...
#7 75.28
#7 75.28 + curl -sLf -o /dev/null 'https://deb.nodesource.com/node_14.x/dists/buster/Release'
#7 75.51
#7 75.51 ## Your distribution, identified as "buster", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
#7 75.51
------
executor failed running [/bin/sh -c apt-get update &&     apt-get upgrade -y &&     apt-get install -y curl &&     curl -kfsSL https://deb.nodesource.com/setup_lts.x | bash - &&     apt-get install -y nodejs &&     apt-get -y clean all]: exit code: 1

**Comment by nigeldunn-pexa** [comment]
Strangely this behaviour isn't mirrored on my personal laptop. I suspect some security tooling may be causing my grief.

**Comment by yeongbin-jo** [comment]
> Strangely this behaviour isn't mirrored on my personal laptop. I suspect some security tooling may be causing my grief.
> 
> Edit: It was caused by a broken SSL chain.

How do you fix the issue? (about a broken SSL chain)

**Comment by yeongbin-jo** [comment]
I solved this issue by disabling ssl certificate validation in some commands. (`curl` and `apt-get`)

```bash
touch /etc/apt/apt.conf.d/99verify-peer.conf \
    && echo >>/etc/apt/apt.conf.d/99verify-peer.conf "Acquire { https::Verify-Peer false }"
echo insecure >> $HOME/.curlrc

curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
apt-get install -y nodejs
npm install -g yarn
```

**Comment by igsu** [comment]
Debian buster is currently supported and any issue during its installation is related to the environment and the network in which the installation is being carried out.

Similar issues with installations on subsystems and behind proxies: #1002 #947 #904 #9 and many more.

It's not a problem related to distributions or compatibility, but to the proxy setup.
