### ISSUE TITLE
Can't install Node 14.x on centos-release-6-10.el6.centos.12.3.x86_64

### ISSUE THREAD

**Issue by olakunlemuheeb** [nodesource/distributions#1240]

**Comment by igsu** [comment]
CentOS 6.x is already EOL.
That is why Node.js 14.x and newer versions are not supported.

**Comment by customautosys** [comment]
> CentOS 6.x is already EOL.
> That is why Node.js 14.x and newer versions are not supported.

Anyone knows any way to install node 14 on CloudLinux 6 (kernel 2.6+, believe the equivalent is CentOS 6)

For some reason NameCheap managed to install node 14 on CloudLinux 6. I am trying to npm install an app, but the native node modules cannot compile due to GLIBC version. I'm hoping to install node 14 on a CentOS 6 docker image and pre-compile the node_modules beforehand.

**Comment by lorand-horvath** [comment]
I'm actually trying to find out how to install Node.js 16 on CloudLinux 6, if at all possible. I have several packages that won't install on the current Node.js 14 version, most important being `sharp` (image processing library) which needs a newer GLIBC version, as mentioned above by @customautosys 

Namecheap support says it can't be done and that Node 16+ will only be supported when they upgrade their servers to CloudLinux 8 (before June 2024).

**Comment by customautosys** [comment]
> I'm actually trying to find out how to install Node.js 16 on CloudLinux 6, if at all possible. I have several packages that won't install on the current Node.js 14 version, most important being `sharp` (image processing library) which needs a newer GLIBC version, as mentioned above by @customautosys 
> 
> Namecheap support says it can't be done and that Node 16+ will only be supported when they upgrade their servers to CloudLinux 8 (before June 2024).

I managed to install node 14 by using alt-nodejs14 from CloudLinux 6.

However, I now have a problem because of a dependency on snappy that I can't even compile because Rust no longer supports GLIBC 2.12.

**Comment by lorand-horvath** [comment]
@customautosys I feel your pain. In my case, I can't install `sharp` because it requires GLIBC 2.17+ for its `libvips` 8 binaries to run.
However, there's no `libvips` binary compiled for CloudLinux (CentOS) 6 / GLIBC 2.12
So, if I want to use `sharp` on Namecheap (still running CloudLinux 6 / GLIBC 2.12) I would have to somehow manually compile/install libvips for that old OS and I haven't had any success yet.

So there's that. Hopefully Namecheap upgrades to CloudLinux 8 soon and Node 16 or 18 will be made available. Node 14 is end-of-life and I think developers should start discussing if it's even safe to use Node 14 at all from a security point of view, on any platform, including shared/cloud hosting.

**Comment by customautosys** [comment]
> @customautosys I feel your pain. In my case, I can't install `sharp` because it requires GLIBC 2.17+ for its `libvips` 8 binaries to run.
> However, there's no `libvips` binary compiled for CloudLinux (CentOS) 6 / GLIBC 2.12
> So, if I want to use `sharp` on Namecheap (still running CloudLinux 6 / GLIBC 2.12) I would have to somehow manually compile/install libvips for that old OS, but I haven't had any success with it yet.
> 
> So there's that. Hopefully Namecheap upgrades to CloudLinux 8 soon and Node 16 or 18 will be made available. Node 14 is end-of-life and I think developers should start discussing if it's even safe to use Node 14 at all from a security point of view, on any platform, including shared/cloud hosting.

Oh I did manage to compile sharp with libvips (after installing a lot of dependencies from source RPMs). Got an email? I can try sending you the one from my node_modules compiled with a CentOS 6 docker image and you can try if it works

**Comment by customautosys** [comment]
@lorand-horvath as luck would have it, namecheap upgraded to CloudLinux 8 and now my node.js website can run https://customautosys.com The problem I am facing now is that again I can't use the latest and greatest directus version again due to glibc incompatibility, because isolated-vm requires 2.29 but I only have 2.28. But now sharp can run.

**Comment by lorand-horvath** [comment]
@customautosys Namecheap hasn't updated to CloudLinux 8 on my server yet, but I really hope they will soon.
Are you on a regular Shared or Premium server?
Am I to think that latest Node.js 18 & 20 are available, but only glibc 2.28 is installed on the server? That's from 2018 according to https://sourceware.org/glibc/wiki/Glibc%20Timeline
Isn't CloudLinux 8 supposed to be a bit more up-to-date?

**Comment by customautosys** [comment]
I'm on a regular shared. I checked the CloudLinux 8 repo and yes, it is glibc 2.28. Quite old. I'm considering a move away from namecheap as its stuff is always old and I'm up for renewal soon. Now considering InMotion and A2 (leaning towards InMotion). Do you know any other good shared webhost which supports node.js (and has updated libs)?

________________________________
