### ISSUE TITLE
NodeJS v4

### ISSUE THREAD

**Issue by STRML** [nodesource/distributions#125]
Tracking issue for PPA supporting Node into the future now that io.js has merged.

**Comment by chrislea** [comment]
4.x builds for debian / ubuntu running now. Repo will be online Soon (tm).

**Comment by chrislea** [comment]
Some things have changed with the `install` target, need to sort them out for the builds to work. Stay tuned.

**Comment by vincentwoo** [comment]
Eagerly awaiting v4 landing!

**Comment by chrislea** [comment]
4.x builds are online now: https://github.com/nodesource/distributions/

**Comment by ewang** [comment]
Some of the Ubuntu distribution versions seem to be missing from the deb repo. I'm getting "Your distribution, identified as "precise", is not currently supported".

**Comment by chrislea** [comment]
Ubuntu Precise is harder to support because the version of `gcc` it ships with is not new enough to compile V8. We're working on a way to deal with this using a different compiler toolchain, but it's (obviously) not trivial to do. We'll keep everybody updated with our progress.

**Comment by anronin** [comment]
is debian wheezy not supported too?

**Comment by tgabi333** [comment]
I'm missing wheezy support too :(

**Comment by chrislea** [comment]
We don't have packages for Wheezy currently. this is because the [version of gcc](https://packages.debian.org/wheezy/gcc) that ships with Wheezy is too old to compile the current versions of V8. Ubuntu Precise has this same issue. Current V8 requires at least gcc 4.8.x.

We're working on getting around this by using a newer compiler toolchain but obviously that's a bit tricky. We'll keep everybody updated on the progress.

**Comment by jcrugzz** [comment]
@chrislea getting the same type of error with trusty

```sh
## Your distribution, identified as "trusty", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

The command '/bin/sh -c curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -' returned a non-zero code: 1
```
Is this expected?

**Comment by rvagg** [comment]
@jcrugzz the script is doing this: 

```
curl -sLf -o /dev/null 'https://deb.nodesource.com/node_4.x/dists/trusty/Release
```

of this if `curl` isn't available:

```
wget -qO /dev/null -o /dev/null 'https://deb.nodesource.com/node_4.x/dists/trusty/Release
```

I guess `curl is available since you're using it, could you try running one of those in your environment and see what they produce? When they fail they produce that message but they're not 404ing for me at least.

**Comment by jcrugzz** [comment]
@rvagg i realized that there was something weird with my docker container. killing it and starting a new one fixed the issue when loading it the next time around. Works now :+1:

**Comment by iancmyers** [comment]
@chrislea I totally understand that supporting Ubuntu Precise is a non-trivial amount of work. I'm wondering if there is a timeline for when that support might be coming? Something as rough as whether this is several weeks out or several months out would be helpful in informing my team's planning.

**Comment by chrislea** [comment]
I'm going more or less off the grid for two weeks at the beginning of
October. Assuming it's a supportable thing I'm hoping to have it done
before I leave.

__
Chris Lea
@chrislea
https://about.me/chrislea

**Comment by chrislea** [comment]
Hi all, a quick update on this. I have node 4.1.1 building on precise currently using a newer compiler toolchain that I've gotten working in our build system. In order to make this all go smoothly, we're going to have to build a ton of additional packages for precise / wheezy so that we can self host the updated toolchain, basically duplicating the work of Matthias Klose on [Launchpad](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/). These builds are running now, and best case they will take a long time to finish but I'll have them to use tomorrow.

Once we have those set up internally, we can get builds out for Precise and Wheezy. **HOWEVER**, be advised ahead of time that doing this install will update `libstdc++` on the target machine to a version that matches this newer compiler. We haven't seen any issues as a result, but proceed at your own risk.

I will update here when when I have additional info.

**Comment by logoff** [comment]
OK. I propose removing Precise and Whezzy from supported distros in the README until these issues get solved.

**Comment by chrislea** [comment]
Which is completely legitimate. But, after a long day today, I am hopeful we'll actually have builds for these distros pushed out within the next 48 hours.

So hopefully the effort will be going into updating the README with the caveats for these older distros rather than removing them in the near term.

If I hit any major speedbumps tomorrow and it looks like we won't push builds before I'm out of pocket for a few weeks, we'll pull these distros from the README as you indicate.

**Comment by logoff** [comment]
I appreciate the effort :smiley: IMHO if a release is considered stable, its documentation should be reliable. Next version could have those distros again, but current one should not. Anyway, if the issue gets solved in the next 72 hours, it would be wonderful. Thank you.

**Comment by chrislea** [comment]
Okay everybody, update time. I'm now kicking around builds of Node 4.1.1 on both `precise` and `wheezy`. Things seem fine thus far. We want to look at them a bit more and then document exactly what we do get these to compile so that people understand what bits they are putting on their machines. This **should** all land later tonight my time (Los Angeles) or in the morning tomorrow. Thanks for your patience!

**Comment by chrislea** [comment]
Aaaaaaand it's all landed. Precise and Wheezy support FTW! You'll all want to read this:

<https://github.com/nodesource/distributions/blob/master/OLDER_DISTROS.md>

I'll leave this open for now in case anybody finds something weird, but will close it in a few days if nothing comes up.

**Comment by STRML** [comment]
Well done Chris!

**Comment by mcollina** [comment]
well done @chrislea!

**Comment by logoff** [comment]
Well done, tank you!

**Comment by tgabi333** [comment]
Great, @chrislea you saved the day!

**Comment by jgonera** [comment]
> PLEASE NOTE that we enable the ubuntu-toolchain-r/test PPA from Launchpad for precise. This is because Clang requires a newer version of libstdc++ than what is available in the distribution itself.

I don't see `libstdc++` among packages in that PPA (https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+packages). Am I missing something?

**Comment by chrislea** [comment]
The libstdc++ packages are part of the newer gcc packages that are in that
PPA.

__
Chris Lea
@chrislea
https://about.me/chrislea

**Comment by imZack** [comment]
@chrislea :+1:, so **arm** builds are not available for these two distributions forever?

**Comment by justcfx2u** [comment]
Any love for the RPM side?

I snagged the .src.rpm for v0.10.40-1 and built new RPMs for v4.1.2 with only a couple tweaks needed. I'm having a little difficulty with the generated RPM as I have not figured out where it's generating NPM dependencies, but was able to install using `rpm -ivh --nodeps nodejs-4.1.2-1custom.el7.centos.x86_64.rpm` and then just ran a `npm install -g benchmark js-yaml json5` afterward.

It wanted:
```
# rpm -ivh x86_64/nodejs-4.1.2-1custom.el7.centos.x86_64.rpm x86_64/nodejs-devel-4.1.2-1custom.el7.centos.x86_64.rpm noarch/nodejs-docs-4.
1.2-1custom.el7.centos.noarch.rpm 
error: Failed dependencies:
        npm(benchmark) is needed by nodejs-4.1.2-1custom.el7.centos.x86_64
        npm(js-yaml) is needed by nodejs-4.1.2-1custom.el7.centos.x86_64
        npm(json5) is needed by nodejs-4.1.2-1custom.el7.centos.x86_64
```

Changes:

* Modify `%doc ChangeLog LICENSE README.md AUTHORS` _to become_ `%doc CHANGELOG.md LICENSE README.md AUTHORS`
* %files devel section ... add:
```
%{_datadir}/doc/node/gdbinit
%{_datadir}/systemtap/tapset/node.stp
```

I have not conducted any further testing at this time.

**Comment by derickbailey** [comment]
what's the word on getting node v4 for RHEL? am i supposed to use the .deb package for it? or will rpm / yum be supported, too?

**Comment by derickbailey** [comment]
after further digging, i see that EL7 is supported in the rpm repo.... it's just not showing up here in the github repository. 

looking at https://rpm.nodesource.com/pub_4.x/el/ - i see a folder for EL7, which is what i need. 

additionally, the setup file at https://rpm.nodesource.com/setup is written more generically now, and doesn't appear to be set to a specific version, like the setup files here in the github repo show. 

so, i think i should be good to go for installing node v4 on RHEL7.

**Comment by justcfx2u** [comment]
Hey, cool. Those look like they were put there in the last day or so, sometime after my last posting.
I'm going to try replacing my builds with the nodesource version and see how it goes!
