### ISSUE TITLE
The certificate chain uses expired certificate for deb.nodesource.com

### ISSUE THREAD

**Issue by shantanoo** [nodesource/distributions#1274]
OS `Ubuntu 20.04.3 LTS`

Command

`curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -`

Error

```
Err:6 https://deb.nodesource.com/node_16.x focal Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 23.55.110.63 443]
```

Failing URLS:

https://deb.nodesource.com-v2.akamaized.net/
https://a1954.dscd.akamai.net/

**Comment by TwilyHoney** [comment]
Facing same problem :)

**Comment by att55** [comment]
Hi.
Please confirm my understanding is correct 🙏🏼 
I think this issue occurred because the URL of setup file used expired root certificate (DST Root CA X3 of Let's Encrypt).
And now, is this issue fixed by changing root certificate?
<img width="488" alt="スクリーンショット 2021-10-08 17 04 33" src="https://user-images.githubusercontent.com/25548003/136522168-1676c4c1-1177-4599-a5bf-fc2b74d06898.png">

**Comment by Anonymous-Hash30** [comment]
For Kali linux users, try this:

```cd /etc/apt/sources.list.d```
after that type ```ls``` and find the list added there, after that, you need to delete that list from directory, you can use this command for the same: ```rm -r <list-name>```

It worked for me.

Try updating again your Kali linux: ```apt update && apt dist-upgrade -y```

Hope this helps.

**Comment by wchargin** [comment]
FWIW, I needed to upgrade *both* `ca-certificates` and `libgnutls30`.

Or, at least, I had this same error on two different machines (a few
days apart from each other). On the one, I upgraded `ca-certificates`
first; on the other, I upgraded `libgnutls30` first. Neither one
sufficed by itself. But on both machines, upgrading *both* packages
unblocked me.
