### ISSUE TITLE
Nodejs Ubuntu installer still installs v4

### ISSUE THREAD

**Issue by ShipmasterKyle** [nodesource/distributions#1322]
I followed the instructions featured on the readme to install v17.x on my Ubuntu Xenial system but after installing when I run
`nodejs --version`
the output is 
`v.4.2.6`
This is the same version I had before. I tried unistalling it and then following the instructions however it doesn't seem to have any impact on the version installed.

**Comment by givetimetolife** [comment]
Me too

**Comment by givetimetolife** [comment]
![image](https://user-images.githubusercontent.com/38744912/146863989-db3f27e4-18a5-4b1e-a0f3-f95f023655bf.png)

env:  Ubuntu 16.04.2

**Comment by givetimetolife** [comment]
![image](https://user-images.githubusercontent.com/38744912/146879869-ea44f704-8567-4c5b-a93a-140a007b2188.png)

I upgraded my operating system so that I can install node normally, But i don't want to do this

`
RUN apt-get update && apt-get upgrade -y -o Dpkg::Options::="--force-confold"

# prepare node env
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get install -y nodejs
`

**Comment by JesusPaz** [comment]
Ubuntu Xenial is currently supported and any issue during its installation is related to the environment and the network in which the installation is being carried out.

Similar issues with installations on subsystems and behind proxies: #1002 #947 #904 #9 and many more.

It's not a problem related to distributions or compatibility, but to the proxy setup.
