### ISSUE TITLE
deb.nodesource.com does not work because it resolves to a server in Russia and Russia is blocking its Internet

### ISSUE THREAD

**Issue by nazarii-kretovych** [nodesource/distributions#1362]
Russia's fascists are blocking access to its part of Internet and we (at least in Ukraine) cannot access deb.nodesource.com, i.e. to install or update NodeJS package. Please don't use Russian severs!!!

**Comment by JesusPaz** [comment]
Hi @nazarii-kretovych, we use an external service to manage our CDN. I will contact them to help you solve this problem. Sorry for the inconvenience.

**Comment by dposhivalnikov** [comment]
> Российские фашисты блокируют доступ к своей части Интернета, и мы (по крайней мере, в Украине) не можем получить доступ к deb.nodesource.com, т.е. установить или обновить пакет NodeJS. Пожалуйста, не используйте русские серверы!!!


Не надо врать! Фашисты - они только в Украине, и именно поэтому Россия очищает Украину от этой нечисти. И врать насчет серверов не нужно!!!!

**Comment by dposhivalnikov** [comment]
> Russia's fascists are blocking access to its part of Internet and we (at least in Ukraine) cannot access deb.nodesource.com, i.e. to install or update NodeJS package. Please don't use Russian severs!!!


Don't lie! Fascists - they are only in Ukraine, and the United States feeds them, and that is why Russia cleanses Ukraine of this evil. And you don't need to lie about servers!!!! There are plenty of proofs of my words, but in the West all the proofs are ignored.

**Comment by nazarii-kretovych** [comment]
> > Russia's fascists are blocking access to its part of Internet and we (at least in Ukraine) cannot access deb.nodesource.com, i.e. to install or update NodeJS package. Please don't use Russian severs!!!
> 
> Don't lie! Fascists - they are only in Ukraine, and the United States feeds them, and that is why Russia cleanses Ukraine of this evil. And you don't need to lie about servers!!!! There are plenty of proofs of my words, but in the West all the proofs are ignored.

@dposhivalnikov You are a stupid Russian pig. Don't listen to Putin's propaganda. The fact is that Russians are fascists because they came to kiill everybody in Ukraine. I recommend you to visit Ukraine and see. Stupid Russian. You don't have enough brains to not believe your Putler Khuilo. You live in a prison. You are not allowed to get information from Internet (Facebook, Instagram). If you mention the word "war", you will be arrested.

**Comment by nazarii-kretovych** [comment]
The west ignores those so-called proofs because they are a part of propaganda. You just don't have brains to understand that.

**Comment by dposhivalnikov** [comment]
> The west ignores those so-called proofs because they are a part of propaganda. You just don't have brains to understand that.

I no longer believe in "propaganda", I fully believe my grandfather, who in World War 2 destroyed Bandera's henchmen, who tortured, raped, killed, slaughtered, tortured the local population of Ukraine. Only the last 30 years after the collapse of the USSR, you have been totally brainwashed from school to the media, impregnating you with negativity and anger towards everything Russian. Believe me, Russian people don't think that way about Ukrainians, they know that there are adequate people in Ukraine. The way you insult and bark at Russians already gives you away as victims of propaganda, and if you don't improve, then, apparently, Russian "Calibers" will help you realize this. And the last... It is absolutely obvious to any adequate person what values Russia stands for, and its Church stands for God and the Law of God. And for what corrupting and dehumanizing values - the West. Therefore, the truth is for the Russians. Delve into the content of Christianity. And what Russia got into you is because you have too much rot. And look inside yourself, you will also find a lot of interesting things. Thank you for the invitation to visit Ukraine, but first talk to your own citizens, with the residents of Donbass - what is it like for them when you destroyed them for 8 years, killing 14 thousand people. Go and talk to him. Anyone can make sure that you are cutting out your own. And garbage dumps like Facebook and Instagram are of little interest to me - they are resources for gathering dirt and fakes, corruption and internal destruction of a person. Good luck. Don't write to me anymore, it won't do any good.

**Comment by nazarii-kretovych** [comment]
@dposhivalnikov Fix your brain, stupid Russian. The whole civilized world is against Russian fascists. Can your stupid zombi brain understand, why is that?

**Comment by nazarii-kretovych** [comment]
North Korea will be your only friend. Russia is becoming North Korea.

**Comment by nazarii-kretovych** [comment]
@dposhivalnikov Ukraine will fight until all the Ukrainian territories, incl. Donetsk, Lugansk and Crimea, are free from Russian criminals. Keep that in mind. The civilized world helps us because this is the right thing to do and because if they don't help, Russia will attack their cities in the future.
