### ISSUE TITLE
[DISTRIBUTION] Support for distribution Ubuntu 22.10

### ISSUE THREAD

**Issue by 64knl** [nodesource/distributions#1461]
**Describe the distribution information:**
 - OS: Ubuntu 22.10
 - Distribution Type: DEB
 - Version 22.10
 - Other info if needed

**Additional context**
Node 19 **is** supported, but the LTS version 16 is not.

## Confirming "kinetic" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists/kinetic/Release'

**Comment by holta** [comment]
> Node 19 is supported, but the LTS version 16 is not.

Just a Clarification:

Node.js 18.x also needs nodesource.com support on Ubuntu 22.10 (Kinetic Kudu).

**Comment by ArtyomVancyan** [comment]
I recommend a temporary solution while the issue is being fixed globally.

I had the same issue after I upgraded my Ubuntu from 22.04 to 22.10, and I wanted to install nodejs 14.x version.

I was following [this](https://linuxize.com/post/how-to-install-node-js-on-ubuntu-18.04/#installing-nodejs-and-npm-from-nodesource) documentation and getting an issue with setting up the needed repository.

After reviewing the code [https://deb.nodesource.com/setup_14.x](https://deb.nodesource.com/setup_14.x), I decided that I need to change the value of `lsb_release -cs` command from `kinetic` to `jammy` (Ubuntu 22.04). So I set `VERSION_CODENAME=jammy` and `UBUNTU_CODENAME=jammy` in `/etc/os-release` file. After this, the repository was successfully added to `/etc/apt/sources.list.d` with name `nodesource.list`. But when I was trying to run `sudo apt-get install nodejs` it still wasn't working (I mean, it was not installing the specified version, but 18.x).

Well, I changed the names of the source lists (adding `.bak` at the end to bring all back after installation). And after I changed all file names starting with `sources.list` I was able to make `nodesource.list` repository more high priority, and the node have been installed with the specified version.

**NOTE:** If you follow my steps above, please do not forget to revert all changes back to the `/etc/os-release` file and rename the `.bak` files back.

Good luck.

**Comment by LinerFox** [comment]
Same issue here. Clean install and then it hits me with this whammy lol.

**Comment by j-arnott** [comment]
Same problem here

No directory exists for:
https://deb.nodesource.com/node_18.x/dists/kinetic/Release
https://deb.nodesource.com/node_16.x/dists/kinetic/Release

**Comment by JesusPaz** [comment]
Changes are in the server to support Ubuntu Kinetic in all the active versions of Node.js, for these to be applied it is necessary to wait for a new version of each one to be published.

**Comment by holta** [comment]
This issue's now resolved for those using Nodesource.com to install Node.js 18.12.0 (LTS) that was published a few hours ago.

(https://github.com/nodesource/distributions#deb somewhat exaggerated support for Ubuntu 22.10 last week, as if it was ready.  Now that claim is becoming more real ;)

**Comment by 64knl** [comment]
Works! Thanks.

**Comment by zomp** [comment]
Could the not-yet-available versions be published manually please? Versions 14 and 16 are still supported, but their releases are rare now (only security ones), so the waiting for the script will take some time.

**Comment by ArtyomVancyan** [comment]
Hi @zomp, you can try the above [solution](https://github.com/nodesource/distributions/issues/1461#issuecomment-1287754723) that I described in detail. I installed version 14, so it should also work for 16 and others.

**Comment by holta** [comment]
> Could the not-yet-available versions be published manually please? Versions 14 and 16 are still supported, but their releases are rare now (only security ones), so the waiting for the script will take some time.

While Nodesource.com could certainly be more prompt, there is an alternative:

```
wget https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.18.0-deb-1nodesource1_amd64.deb
apt install ./nodejs_16.18.0-deb-1nodesource1_amd64.deb
```

Done!  Same for any other version of Node.js like 14.x or whatever &mdash; i.e. just browse their download site for the latest, e.g.:

```
wget https://deb.nodesource.com/node_14.x/pool/main/n/nodejs/nodejs_14.20.1-deb-1nodesource1_amd64.deb
apt install ./nodejs_14.20.1-deb-1nodesource1_amd64.deb
```

Etc!

**Comment by zomp** [comment]
Thank you, guys. I overlooked the original packages are so much release independent. I expected dependencies on libs and other packages in specific versions. :+1:
