### ISSUE TITLE
Nodejs 14 distribution with weird content under usr/lib/node_modules/npm/docs/

### ISSUE THREAD

**Issue by nichoio** [nodesource/distributions#1466]
I stumbled upon weird content in the Nodejs 14 distribution and wonder if it's bloatware. I'm talking about this distro:  
https://deb.nodesource.com/node_14.x/pool/main/n/nodejs/nodejs_14.20.1-deb-1nodesource1_amd64.deb

This package also contains following directory: `./usr/lib/node_modules/npm/docs/`.  
Checking with `dpkg -c nodejs_14.20.1-deb-1nodesource1_amd64.deb | grep ./usr/lib/node_modules/npm/docs` for example, we see a bunch of weird files at the top level of this path, e.g. `gatsby-browser.js`. Looks like this stems from this repo:  
https://github.com/tanyabrassie/npm-cli

In `./usr/lib/node_modules/npm/docs/package.json`, the name is "npm-cli-docs". A package by the same name is flagged [as malware in NPM](https://www.npmjs.com/package/npm-cli-docs).  
I didn't check your other Nodejs distros in detail but looks like current node_16.x doesn't contain these files. I haven't looked into the other node_14.x distros though.

**Comment by riosje** [comment]
Hi @nichoio let's cut this in some pieces:

- Node **14.20.1** comes with [NPM CLI](https://github.com/npm/cli) version **v6.14.17**, you can find the release of that build the NPM repo -> [v6.14.17](https://github.com/npm/cli/releases/tag/v6.14.17) if you download this build you can find the same files within the docs folder

- If you build `make docs` the docs locally for the version [6.14.17 ](https://github.com/npm/cli/commit/97497f188e3a60cd3bba8ae70c72e0b581fb6c43) you can find within the docs folder the same files and package version.
-------
### Some Timeline Event Correlation

**I can find is that the NPM package has been removed around a year ago.**
![image](https://user-images.githubusercontent.com/55195249/199058482-e430aecf-a54f-4cfd-affa-60bee77e1472.png)

**And the NPM CLI version 6.14.17 has been released on April 28 this year**
![image](https://user-images.githubusercontent.com/55195249/199058736-7b72f42f-3e70-4aae-9432-ef0fb0ad8fd2.png)

Since the NPM package [npm-cli-docs](https://www.npmjs.com/package/npm-cli-docs/v/0.0.1-security) has been removed before than the NPM 6.14.17 release, I can't affirm that NPM CLI has this malicious package within his deps.

based on above things I don'd think that the NPM CLI DOCS contain any kind of malware, but o can't give any guarantee of that, just in case that you think it is possible they have some kind of malware within their code I encourage you to rise a an issue on the NPM CLI repo to remove it ASAP.
finally here at Nodesource we only package and distribute the nodejs DEB and RPM as it comes from the source https://nodejs.org/
