### ISSUE TITLE
[ERROR] Node.js XX on UbuntuXX Installation fail

### ISSUE THREAD

**Issue by AftabAhmedAbro** [nodesource/distributions#1541]
**Describe your bug**
I am getting this issue always whenever I try to upgrade my node version using ubuntu command

'''
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_19.9.0-deb-1nodesource1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
'''

**Distribution Information:**
 - OS: Ubuntu 20.04

**Node Version:**
 - Node: 14.17.xxx

**Expected behavior**
It needs to upgrade my nodejs version to 19+ 

**Screenshots**
![image](https://user-images.githubusercontent.com/73740818/231863882-6e1b5880-c7b0-480b-8212-5093acf51ea8.png)

**Comment by bjnaga** [comment]
Try this code it will install nodejs_19.9.0 

```
sudo dpkg -i --force-overwrite /var/cache/apt/archives/nodejs_19.9.0-deb-1nodesource1_amd64.deb
```

**Explanation**: 
the downloaded file is saved in  /var/cache/apt/archives/ file all you need to do now i forcefully install `.deb` package 
manually, i was able to install version 18 LTS easily with this method 
![Screenshot from 2023-04-15 18-11-44](https://user-images.githubusercontent.com/2216655/232224602-ebbb4f4d-2aa0-4dcc-ad48-6b43959f595c.png)

there is a slight change my command because I'm already in the `/var/cache/apt/archives/`  directory.

Let me know if your need more help

**Comment by AftabAhmedAbro** [comment]
let me try this

**Comment by Grothesk242** [comment]
Just deinstall libnode-dev
It does not fit to the nodesource packaged variant anyway. 
And this is exactly what apt/dpks is telling you.

**Comment by JesusPaz** [comment]
you can try deleting your current node version and installing the one you need. Maybe this issue will help #191
