### ISSUE TITLE
[ERROR] Node.js 15 missing bookworm distribution

### ISSUE THREAD

**Issue by bdaileycrowe** [nodesource/distributions#1582]
**Describe your bug**

**Distribution Information:**
 - OS: Ubuntu

**Node Version:**
 - Node: v15.x

**Expected behavior**
Node installs

![image](https://github.com/nodesource/distributions/assets/136755952/865784a9-57b2-4f4d-9b59-4fdf77b0bbd9)

**Additional context**
I know 15.x is no longer supported, but other distro's are still there, except for bookworm. Wanted to know if this was intended

**Comment by riosje** [comment]
Hello, yes it is intended, when a node version reach the end of support we do not distribute it anymore on newest versions.
you may want to use Node16 or Node18 instead
https://nodejs.dev/en/about/releases/

**Comment by bdaileycrowe** [comment]
i am confused. why are other distributions for 15.x still available?

**Comment by riosje** [comment]
@bdaileycrowe what you mean?
can you provide some example plz?

**Comment by bdaileycrowe** [comment]
If I try to download 15.x for Xenial (for example), it will work as the release is still present here: https://deb.nodesource.com/node_15.x/dists/ 

The bookworm distribution is missing as of yesterday, but other 15.x distributions are still present

**Comment by riosje** [comment]
ok got you.
this is because at the date of the last release of Node15 debian bookworm did not exist, and after a node version reach the EOL we do not package it anymore for the newest versions.
The scripts to package and distribute node15 are not executed anymore for this reason there will not be more packages of node15 for the newest versions of debian.
