### ISSUE TITLE
[DISTRIBUTION] Support for distribution system-release-2-14.amzn2.aarch64 and system-release-2-14.amzn2.x86_64

### ISSUE THREAD

**Issue by sopeters** [nodesource/distributions#1604]
**Describe the distribution information:**
 - OS: Amazon Linux 2
 - Distribution Type: RPM
 - Version: 20.04
 - Other info if needed

**Additional context**

Getting below when running

```curl –sL https://rpm.nodesource.com/setup_20.x |bash -```

\#\# Your distribution, identified as "system-release-2-14.amzn2.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

\#\# Your distribution, identified as "system-release-2-14.amzn2.aarch64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by riosje** [comment]
hello is not possible to run NodeJS 20 in Amazon Linux 2 because it has not GLIBC version 2.28 or higher.
You must update your SO to Amazon Linux 2023 or any other distro which has GLIBC >= 2.28.

This was already discussed in several issues in the official Nodejs repo
https://github.com/nodejs/node/issues/43246

Some guys try to blame us about this, but the fact is that we do not build the NodeJs binaries, having said that we can do nothing about this.
