### ISSUE TITLE
Ubuntu 15.10 (Wily Werewolf) is not supported

### ISSUE THREAD

**Issue by mkg20001** [nodesource/distributions#162]
Please add Support for Ubuntu 15.10 Wily Werewolf

**Comment by chrislea** [comment]
Wily is supported on Node >= 4.2.x.

```bash
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
```

should install it for you.

**Comment by mkg20001** [comment]
It´s not supported in https://github.com/nodesource/distributions/blob/master/deb/setup_0.12

**Comment by chrislea** [comment]
That's correct. Wily is only supported for Node >= 4.2.x.

**Comment by mkg20001** [comment]
and why?

**Comment by chrislea** [comment]
There is apparently a bunch of stuff that's just fundamentally broken in 0.12 and isn't going to get fixed. Things that have subsequently been fixed in 4.x. So the goal is to get everybody moved to 4.x as soon as possible as it's a pretty easy upgrade path. The 0.12 series is in "maintenance mode" now, meaning it's only going to get looked at if there is some kind of critical security bug.

There are some docs [here](https://nodesource.com/services/upgrade-self-service) that might prove useful / helpful with upgrading.

**Comment by mkg20001** [comment]
and whats the newest node version?
12 or 4??? or ...

**Comment by chrislea** [comment]
Newest is 4.2.1.

https://nodejs.org

**Comment by pete-otaqui** [comment]
@mkg20001 It's not referring to version **12** it's version **0.12**, that is: *less than version 1.0* (and a lot less than 4.2.1)
