### ISSUE TITLE
[ERROR] Node.js 18 on Ubuntu 22.04.3 LTS Installation fail

### ISSUE THREAD

**Issue by we1rdw4y** [nodesource/distributions#1684]
**Describe your bug**
Apt skips nodesource' repositories on `sudo apt update` with error
```
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://deb.nodesource.com/node_18.x nodistro InRelease' doesn't support architecture 'i386'
```

**Distribution Information:**
 - OS: Ubuntu
 - Version 22.04.3 lts
 - Arch: amd64

**Node Version:**
 - Node: Node.js v18.x

**To Reproduce**
1. execute steps from https://github.com/nodesource/distributions#installation-instructions
2. after step 2 got err "repo doesnt support i386"

**Expected behavior**
apt package index resync

**Screenshots**
![error](https://github.com/nodesource/distributions/assets/1389391/cb7af053-7de3-499a-b3b5-5d50318cc275)
![arch](https://github.com/nodesource/distributions/assets/1389391/36cba6ae-30f1-406f-8c16-2fd17b810470)

**Additional context**
fix:
after step 2 `sudoedit /etc/apt/sources.list.d/nodesource.list` :
```
deb [arch=amd64 signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main
```
thx @o-alquimista #1501

**Comment by mlippert** [comment]
The PR should fix the issue. But for those that don't understand **_why_** they got the apt error...

It is very likely that you have multi architecture configured, so that both the native architecture (probably `amd64`) _AND_ the additional `i386` architecture are looked for unless the apt source specifies which architecture to get from the apt repository (`[arch=amd64]` in a `.list` file). This [ask Ubuntu answer](https://askubuntu.com/a/741411) has more info (although it's about a different repo)

**Comment by JesusPaz** [comment]
Thanks for your contribution, this issue is resolved by https://github.com/nodesource/distributions/pull/1739
