### ISSUE TITLE
[DISTRIBUTION] Support for Ubuntu 23.10 Mantic Minotaur

### ISSUE THREAD

**Issue by yktoo** [nodesource/distributions#1710]
**Describe the distribution information:**
 - OS: Ubuntu
 - Distribution Type: DEB
 - Version: 23.10

Please add binary builds for the recently released **Ubuntu 23.10 Mantic**. Thanks!

**Comment by riosje** [comment]
Hi @yktoo our packages are already available, we have to do nothing to support a new distro.
We recently re-designed the whole repo and almost every DEB distro is supported.
Just follow the readme instructions.

![image](https://github.com/nodesource/distributions/assets/55195249/02249bbe-8917-4a36-81da-f904241facfc)

**Comment by yktoo** [comment]
@riosje As far as I understand, you now publish distro-agnostic builds of Node under `nodistro`?

By the way, getting the below warning from apt:

```
N: Skipping acquisition of configured file 'main/binary-i386/Packages', as repository 'https://deb.nodesource.com/node_20.x nodistro InRelease' doesn't support architecture 'i386'
```

To get rid of it, I had to explicitly specify the `arch`:

```
deb [arch=amd64 signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
```

**Comment by riosje** [comment]
Yeah!!
Good catch, We've created an script to properly configure the repository, since a lot of people are struggling with this.
We've not published it as the main installation way yet because we want to test this for a couple of weeks more.
But you can try it.
https://github.com/nodesource/distributions#installation-scripts
