### ISSUE TITLE
[ERROR] Node.js 16 on Debian Slim 12 what about npm?

### ISSUE THREAD

**Issue by feluxe** [nodesource/distributions#1725]
**Describe your bug**
I just tried to install node 16 via docker, but the npm command doesn't seem to be there. I couldn't find any mention in the README.

**Distribution Information:**
 - OS: `Debian Slim`
 - Version: `12`
 - Docker: `python:3.9-slim`

**Node Version:**
 - Node: `Node.js v16`

**To Reproduce**
I have this in the `Dockerfile`:

```Dockerfile
FROM python:3.9-slim

RUN apt-get update
RUN apt-get install -y ca-certificates curl gnupg
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
ENV NODE_MAJOR=16
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt-get update
RUN apt-get install nodejs -y

# This fails:
RUN npm -v
```

**Expected behavior**
I was expecting `RUN npm -v` to work.

**Comment by jaxn** [comment]
This seems to be the same as #1601 

The workaround / fix is to pin `deb.nodesource.com` first. This updated Dockerfile works:

```
FROM python:3.9-slim

RUN apt-get update
RUN apt-get install -y ca-certificates curl gnupg
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
ENV NODE_MAJOR=16
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

# tmp fix for bug https://github.com/nodesource/distributions/issues/1601
RUN echo "Package: nodejs" >> /etc/apt/preferences.d/preferences; \
    echo "Pin: origin deb.nodesource.com" >> /etc/apt/preferences.d/preferences; \
    echo "Pin-Priority: 1001" >> /etc/apt/preferences.d/preferences;

RUN apt-get update
RUN apt-get install nodejs -y

# This works now:
RUN npm -v
```

**Comment by riosje** [comment]
Guys still facing the same issue?

**Comment by jaxn** [comment]
Yes, the dockerfile @feluxe posted still fails to build with the same error.

The problem is that `bookworm` images have a `nodejs` package in the default repos, whereas `'bullseye` does not. And that the requested `NODE_MAJOR` results in an older version than the default system nodejs.

Running `apt policy nodejs` from the shell of the `Dockerfile` above, you get output like:
```bash
# apt policy nodejs
nodejs:
  Installed: 18.13.0+dfsg1-1
  Candidate: 18.13.0+dfsg1-1
  Version table:
 *** 18.13.0+dfsg1-1 500
        500 http://deb.debian.org/debian bookworm/main arm64 Packages
        100 /var/lib/dpkg/status
     16.20.2-1nodesource1 500
        500 https://deb.nodesource.com/node_16.x nodistro/main arm64 Packages
     16.20.1-1nodesource1 500
     ...
```

The default `nodejs` available on `bookworm` does not bundle npm with it. That is a separate install:
```bash
# apt policy npm
npm:
  Installed: (none)
  Candidate: 9.2.0~ds1-1
  Version table:
     9.2.0~ds1-1 500
        500 http://deb.debian.org/debian bookworm/main arm64 Packages
```

The result is that unless `deb.nodesource.com` is pinned, the system `nodejs` is installed (v18 and without `npm`).

This issue exists on `bookworm` when the desired `NODE_VERSION` is lower than the default system version (which is currently `18.13.0+dfsg1-1`).  If the above `Dockerfile` set `NODE_MAJOR=18`, then it would have installed `18.19.0-1nodesource1` instead.

My suggestion is that the docs should recommend pinning nodesource when using `bookworm` images.

**Comment by jaxn** [comment]
I'm happy just adding this to the dockerfile:
```
RUN echo "Package: nodejs" >> /etc/apt/preferences.d/preferences; \
    echo "Pin: origin deb.nodesource.com" >> /etc/apt/preferences.d/preferences; \
    echo "Pin-Priority: 1001" >> /etc/apt/preferences.d/preferences;
```

The installation script just does the same thing but also installs adds the `nsolid` repo.  I'd rather not add a script like that to a dockerfile.

**Comment by JesusPaz** [comment]
This problem is solved by the installation script. Node.js v16 is deprecated, it is recommended to use a newer version. 

```
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - &&\
sudo apt-get install -y nodejs
```

**Comment by diepes** [comment]
I just ran into the same problem, using nodesource and apt.

It would be great if the apt instructions included the pin option.

**Comment by jfo8001** [comment]
I just ran into the same issue - node 18.19.0 has no npm included.  This used to work in node 18.  
Would appreciate current instructions for debian.
