### ISSUE TITLE
[ERROR] Node.js 20 on RHEL9 Installation fail

### ISSUE THREAD

**Issue by vehagn** [nodesource/distributions#1792]
**Describe your bug**
Instructions on how to install Node 20 on https://rpm.nodesource.com/ fails GPG check.
```
~$ sudo yum install https://rpm.nodesource.com/pub_20.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
~$ sudo yum install nsolid -y
```

I think a quick solution would be to update the webpage using the solution @riosje posted in in https://github.com/nodesource/distributions/issues/1776#issuecomment-2015359783

**Distribution Information:**

- OS: UBI
- Version: 9
- Docker image (sha256:1fafb0905264413501df60d90a92ca32df8a2011cbfb4876ddff5ceb20c8f165)

**Node Version:**

- Node: 20

**To Reproduce**

```shell
docker run -it --rm redhat/ubi9@sha256:1fafb0905264413501df60d90a92ca32df8a2011cbfb4876ddff5ceb20c8f165
yum install https://rpm.nodesource.com/pub_20.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
yum install nsolid -y
```

Error:
```
Nsolid Packages for Linux RPM based distros - aarch64                                                                               1.6 MB/s | 1.7 kB     00:00    
Importing GPG key 0x9B1BE0B4:
 Userid     : "NSolid <nsolid-gpg@nodesource.com>"
 Fingerprint: 6F71 F525 2828 41EE DAF8 51B4 2F59 B5F9 9B1B E0B4
 From       : /etc/pki/rpm-gpg/NODESOURCE-NSOLID-GPG-SIGNING-KEY-EL
warning: Signature not supported. Hash algorithm SHA1 not available.
Key import failed (code 2). Failing package is: nsolid-20.11.1-ns5.0.5.aarch64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/NODESOURCE-NSOLID-GPG-SIGNING-KEY-EL
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: GPG check FAILED
```

**Expected behavior**
I expect Nsolid/NodeJS to be installed

**Additional context**
Add any other context about the problem here, specify if already has another NodeJS version or if trying to re-install the current version.

**Comment by riosje** [comment]
Hi @vehagn thanks for reaching us with this issue.
As I mentioned in the other Issue In past year we made a mess with the docs and well, here we are...

This `RPM` package `https://rpm.nodesource.com/pub_20.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm` all what it does is create the  repo in `/etc/yum.repos.d/` and installs a GPG key that we used to use to sign the packages(not anymore) that key is `SHA1` which is deprecated since RHEL9 versions.

For that reason we've created a new key with **SHA256** `https://rpm.nodesource.com/gpgkey/ns-operations-public.key`.
I encourage you to not use anymore this package `https://rpm.nodesource.com/pub_20.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm` to setup the repo better use the script.

**Comment by vehagn** [comment]
Thanks for your quick reply!

I was able to modify the script you provided for my purposes (hence the PR I opened). My request is for you to update the webpage (https://rpm.nodesource.com/)so others don’t try (and fail) to use the same snippet. 

I’d be happy to update the webpage/docs if you could point me in the right direction.

**Comment by riosje** [comment]
ey @vehagn thanks for noticing that.
I almost forgot that site, I'll be fixing it soon.
