### ISSUE TITLE
RHEL/CentOS 7 repomd.xml timestamp issue

### ISSUE THREAD

**Issue by tsde** [nodesource/distributions#184]
Hi,

FIrst, thank you for your work on maintaining deb/rpm repos for NodeJS. I recently faced an issue with RHEL/CentOS 7 regarding the repomd.xml file.

I use Puppet to manage my boxes and one thing it does is keeping nodejs package up to date. I was running nodejs 0.12 and tried to update to 4.x (i.e. change baseurl in the repo file from `.../pub_012/... to .../pub_4.x/...`) and failed to do so for a simple reason (but kinda hard to identify): the repomd.xml timestamp from the EL7 0.12 repo is more recent that the one from the EL7 4.x repo (11/26 and 11/12 respectively).

So each time Puppet runs, the `yum check-update` command issued behind the scene drops the following warning:

`Not using downloaded repomd.xml because it is older than what we have`

and package doesn't get updated.

The only work-around so far is to issue a `yum clean metadata` before trying to update the package but in my case, this is a not a "clean" solution.

Note that there's no problem if you try to upgrade from 0.10 -> 0.12 or 4.x -> 5.x as the repomd.xml timestamps are "logically set".

I think you first provided EL7 rpm repos for node v4 and v5 and only after provided repos for v0.10 and 0.12. But the strict (annoying) behavior of yum makes package upgrades not run as smooth as they should.

Is there a way for you to simply update the timestamps of EL7 repomd.xml for node 4.x and 5.x ?

Thanks

**Comment by chrislea** [comment]
Hrm, okay, that's a new one.

Yes, you're mostly correct about the cause and effect issue. What happened is that there has been a 0.12.x release that happened more recently than the last 4.x or 5.x release. But, this is likely to happen again in the future. Let me think a bit about this to see if there is a clean way to resolve the problem.

**Comment by tsde** [comment]
@chrislea Cool, thanx for your concern :)

**Comment by laszlof** [comment]
Bumping this issue. This is still a problem.

Recently switched the nodesource RPM out from the 6.x to 9.x versions, when yum tried to make the cache file, it complained that repomd.xml was newer than the version it was downloading, and wouldnt update the cache.

This is a serious problem for anyone trying to update with any kind of automation (in my case, via ansible). The root cause I think is the fact that nodesource uses the same repo name for all its versions. Ideally, it should have a separate reponame for each version so that there is no chance of polluting the cache if you ever change versions.
