### ISSUE TITLE
Clean npm installation in pre-install

### ISSUE THREAD

**Issue by rvagg** [nodesource/distributions#188]
Suggested by @chalker and I agree this is a good idea:

During pre-install we should be doing an `rm -rf /usr/lib/node_modules/npm/` so that if there is a previous installation of npm it'll start from scratch rather than just adding new files to the directory. @chrislea what do package managers do for us in this area? Can they guarantee a clean directory before installing or do we have to explicitly do the removal? We've had some problems with upgrades from v4.x (and prior) to v5.x because npm v3 in v5.x is a heavy rewrite and a lot has changed on the filesystem.

**Comment by chrislea** [comment]
This is easy to do, actually. Both Debian and RH have provisions for "run this script pre-install" so I can check for the existence of that directory and remove it if it's there. Do we want to try and get this in for the security updates that are landing soon?

**Comment by chrislea** [comment]
Okay I believe I have this working for Debian / Ubuntu. Will look at RH next.

Just to play devil's advocate though, are we *sure* we want to do this? Because if we have an end user that has installed something globally for `npm` and they upgrade even inside a point release, like from 4.2.2 to 4.2.3 or something, it will wipe out their globally installed stuff.

I know that in an ideal world, people aren't supposed to do global installs, but in the world we actually live in this is likely to break something for somebody.

**Comment by ChALkeR** [comment]
@chrislea If a user manually updated npm globally, updating Node.js package (with npm update inside) version could break such install. Even with a 0.12.* → 0.12.* update.

**Comment by chrislea** [comment]
@ChALkeR fair enough. There is a security update coming Soon (tm) and this change should go out with those new builds. /cc @rvagg

**Comment by robations** [comment]
> cleaning the npm directory could already break such install

I already find that every time I update Node.js 4.x using apt, npm reverts from v3 to v2, which breaks any install scripts I have. Not sure if this is by design or a bug.
