### ISSUE TITLE
No Ubuntu 15.10 package

### ISSUE THREAD

**Issue by nikolay** [nodesource/distributions#189]
Ubuntu 15.04 will become EOL next month and you still don't have a 15.10 package and it was release two months ago. I'm pretty sure there are no major differences between 15.04 and 15.10, so, please, add 15.10 to the repositories. Thanks!

**Comment by chrislea** [comment]
I'm not sure what you mean, but if you look [here](https://github.com/nodesource/distributions/#deb) we certainly do support 15.10. We started pushing those packages out when 15.10 hit RC status.

**Comment by nikolay** [comment]
@chrislea Thanks, but how do I install the latest stable (without knowing if it's 5.x or 6.x or whatever) with the packges?

**Comment by chrislea** [comment]
Well, you have to know what you want to install first, so I'd recommend reading [this](https://nodejs.org/en/blog/community/node-v5/). Then look [here](https://github.com/nodesource/distributions#debinstall) and install 4.x or 5.x depending on what you want.

**Comment by nikolay** [comment]
@chrislea I know the difference between v0.10, v4, v5, and so on, but I am working on a script to setup a developer-oriented Virtual Linux Desktop and wanted to install the latest version of Node.js without adding yet another configuration option. For example, your old PPA worked that way - you just add the PPA to the distro and you know you always get the latest (of course, this was before the multitude of options). It just would be nice to have some way to always install the latest stable without caring which it is exactly.

**Comment by chrislea** [comment]
That's just not really feasible given the way Node is currently being developed. It's why we keep separate repos for 4.x and 5.x, because we don't want anybody to have a major upgrade happening without them explicitly knowing what's going on. If what you're looking for is stability, then use the 4.x repo and you'll be getting the LTS releases for a long time and you won't have to think about anything else.
