### ISSUE TITLE
Stable repo

### ISSUE THREAD

**Issue by tjconcept** [nodesource/distributions#195]
Like `https://deb.nodesource.com/node_5.x/...` why not have `https://deb.nodesource.com/stable/...` and possibly `https://deb.nodesource.com/lts/...`?

If you need certainty that you can spin up something with a specific version of Node.js (tested and tried), I don't think you should install from an external source like this. Better alternatives include a docker build.
For docker files etc. it makes more sense to fetch the stable versions of all software, run all tests, and then promote *the build* for production.

**Comment by chrislea** [comment]
We can't just have repos like `stable` and `lts` because we're supporting too many versions. For example, both `0.12.x` and `4.2.x` are currently `LTS` releases. Also, when stable switches from `5.x` to `7.x` at some point in the future, people may still want to stick with `5.x` for as long as it's supported. Basically, we are copying what Ubuntu and other Linux distros that have to potentially support many versions simultaneously do, and just use version numbers.

Yes, it would be nice to have fewer repos, but no solution is ideal and this is the one we are running with.

We already make docker builds for each release if you'd rather use those.

**Comment by tjconcept** [comment]
> Also, when stable switches from `5.x` to `7.x` at some point in the future, people may still want to stick with `5.x` for as long as it's supported. 

Just settle on something. `LTS` and `stable` could be the newest available (I think that would make the most sense).
People who want to stick with `5.x` should not use `stable`. And if they use `stable` anyway, they should be the ones doing maintenance.

> Basically, we are copying what Ubuntu and other Linux distros [..]

I might be missing something here, but that is not how it is typically done in the Debian/Ubuntu world. Nginx (http://nginx.org/packages/debian) and MongoDb (http://repo.mongodb.org/apt/debian/dists/wheezy/mongodb-org/stable) for instance both have stable branches that automatically updates.
If you want it like regular Debian packages, you should only have one repository (node-version neutral name) containing whatever LTS version is available at the freeze time of the specific Debian release.

> Yes, it would be nice to have fewer repos, but no solution is ideal and this is the one we are running with.

I actually don't think there should be fewer repos. Choice is good. I don't know anything about the build process, but I hope it's all automated so that the repos are mostly free? I would compare them to Git branches.

Forgive me, I'm really bad at accepting the state if I don't understand the reasoning.

**Comment by chrislea** [comment]
The thing that's been settled on (by the Node.js Foundation) is that there will be multiple "LTS" and "stable" versions supported at any one time.

The examples you cite with Nginx and MongoDB are not applicable to our situation. In both of those cases, they have a single "stable" and a single "dev" release at any one time (Nginx calls their dev channel "mainline" now).

What is applicable is what Canonical is doing with their Ubuntu releases. For example, at the time of this writing, both Ubuntu Precise and Ubuntu Trusty are supported LTS releases. Also, currently, both Ubuntu Vivid and Ubuntu Wily are supported stable releases. This is why Canonical doesn't just have repos for something like "LTS" and "current", because there are more than one release in either of those categories.

What we are doing is the same thing. Currently 0.12.x and 4.2.x are simultaneously supported as LTS. In the future, it's likely that both 5.x and 7.x will be simultaneously supported as stable.

We don't want to make a "stable" repo that just tracks the newest stable release, because that would mean that some day in the future it would just jump from 5.x to 7.x and given the pace of Node development that would break tons of things for people (this happened back in the day when I was maintaining a "current" repo on Launchpad, and it jumped one day from 0.6 to 0.8, and there was generally just a ton of mayhem when peoples' machines updated).

We debated this for a while internally and the decision was that it was worth making sysadmins consciously decide which repo(s) they should subscribe to so that there would be no chance of a version bump that would break currently working codebases getting pushed out without any warning.

**Comment by tjconcept** [comment]
I think I see the problem. You basically want to fit into the common package-scheme (which has just one package with a given version per OS-release) but still provide a bunch of versions on each release so you end up maintaining each combination of the two and as a side-effect some common practices are lost.

As a Ubuntu/Debian user, I expect that if I change the release name in my sources I would get different versions of my packages. I don't manually update the repository of Gimp to go from `1.x` to `2.x`, and I don't expect backwards compatibility when upgrading my release either.

> this happened back in the day when I was maintaining a "current" repo on Launchpad, and it jumped one day from 0.6 to 0.8, and there was generally just a ton of mayhem when peoples' machines updated

I don't think you're supposed to do that :P I've only seen major updates for new OS releases.

Anyway, thanks for taking your time to respond :-)
