### ISSUE TITLE
[FAIL] docker debian installation

### ISSUE THREAD

**Issue by a93ushakov** [nodesource/distributions#203]
Hello,
I use `Docker` as `nodejs` wrapper, and I couldn't install fresh `nodejs` and `npm` via this `Dockerfile`:
```sh
FROM debian:latest

# switching to belarus debian repos
RUN \
	rm \
		/etc/apt/sources.list

ADD sources.list /etc/apt/

RUN \
	apt-get \
		update && \
	apt-get \
		upgrade

RUN \
	apt-get \
		install \
			-y \
			--no-install-recommends \
				curl \
				build-essential

RUN \
	curl -sL https://deb.nodesource.com/setup_5.x | bash - && \
	apt update && \
	apt-get install --yes nodejs 

RUN \
	useradd \
		-ms \
			/bin/bash \
				docker

RUN \
	rm \
		-rf \
			/var/lib/apt/lists/*

WORKDIR /home/docker/

USER docker

```
Can you help?

**Comment by a93ushakov** [comment]
`npm -v` and `node -v` commands are unavailable.

**Comment by wblankenship** [comment]
Hey @a93ushakov,

Thanks for using these repos and opening an issue. I love your indentation for the Dockerfile, its super easy to read!

A few things.

1.

This script is installing the default Node.js package for Debian Jessie. You can verify this by calling `nodejs -v` which yields `0.10.29`. This is caused by the command `curl -sL https://deb.nodesource.com/setup_5.x` failing due to a certificates error. It never populates the `sources.list` file for you. You could bypass this error using the `--insecure` flag on curl, but use that at your own risk.

2.

Your line `rm -rf /var/lib/apt/lists/*` is making your image larger, not reducing its size, because of the way layered file systems work. I would recommend moving that command to the end of every `RUN` command that uses apt.

3.

The default for the `debian:jessie` sources.list file is to use the `httpredir` service from the Debian project, which intelligently selects a local mirror with high bandwidth for you. You may see reduced performance if you pin to a specific repo. Unless you have a specific use case that calls for the Belarus mirrors, the default may work better. For more information, refer to: http://httpredir.debian.org/

4.

We have some pre-baked Docker images based on `debian:jessie` where I have shaved most of the yaks involved with getting Node.js into a Docker image. You can check them out here: https://github.com/nodesource/docker-node

If you want to bake it into your own image, you can either use `FROM nodesource/jessie:argon` or you can copy-pasta the good parts from the Dockerfiles in that repo.

I hope this helps! :smile:

**Comment by a93ushakov** [comment]
thanks 4 reply, @wblankenship .
