### ISSUE TITLE
Centos 6.7 not supported

### ISSUE THREAD

**Issue by codecowboy** [nodesource/distributions#205]
I have a client on Centos 6.7 and want to run 
```
curl --silent --location https://rpm.nodesource.com/setup_4.x | sudo bash -
```
But get the following error:

## Your distribution, identified as "centos-release-6-7.el6.centos.12.3.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

Is there a version which will work with 6.7 ?

**Comment by xzr** [comment]
+1, was trying a similar setup just a minute ago

**Comment by acorncom** [comment]
Per https://github.com/nodesource/distributions#enterprise-linux-based-distributions, you should be using 0.12 instead of 4.x, but per #197 it's not working.  The reason I saw your issue report is I'm running into the same problem ;-)

**Comment by codecowboy** [comment]
@acorncom thanks. I installed via nvm instead which seems to work. Centos 6.7 is a pain for just about everything but hosting companies seem to like it :( I need 4.x, not 0.12

**Comment by Alexander-OFM** [comment]
Same problem here. At https://rpm.nodesource.com/pub_4.x/el/ there is no 6 directory. Where can I download the rpms by hand?

**Comment by triccardi-systran** [comment]
The issue is probably that node v4 is not buildable with the default compiler on redhat-6, because it doesn't support C++11; see this warning for ubuntu/debian: https://github.com/nodesource/distributions/blob/master/OLDER_DISTROS.md

If it's the reason, then it should be documented on the main readme and on this documentation too.

**Comment by chrislea** [comment]
Yes, the reason as indicated is that you can't compile modern versions of V8 with the compiler that ships in EL6. This issue is being tracked in #128.

It is noted in [the README](https://github.com/nodesource/distributions/#rpm) as we say packages for EL6 are available for Node < 4.x.

We'll updated the original issue when we have any new progress to report. Thanks.

**Comment by triccardi-systran** [comment]
The README states that there is no node 4 for EL6, but doesn't say why. Maybe a link to the issue #128 would help avoiding being spammed by new duplicate issues.
