### ISSUE TITLE
Ubuntu 16.04 Xenial

### ISSUE THREAD

**Issue by The-Technicalist** [nodesource/distributions#258]
I know it's still in testing and not officially released yet, but is there a update coming? I'm trying to set up  Mean  Stack on Ubuntu 16.04 So support would be appreciated.

Until, the version it lets me install is 4.2.6
```
nodejs --version
v4.2.6
```

**Comment by chrislea** [comment]
We don't support pre-release versions of Ubuntu in general. Once the RC for Xenial comes out, depending on what we see in the community, we may start pushing builds at that time. Once Xenial is officially released we will support it right away.

If you're trying to set up a MEAN stack and are using something like Ansible to do it, I'd recommend just testing against Wily as there probably won't be any discernible differences to the setup. Then when Xenial is released you can just run your playbook(s) against the updated distro.

**Comment by robfrawley** [comment]
@The-Technicalist: The packages build for Wily have worked without any issue on my development machine running Xenial since the first alpha release, and prior to that the Vivid packages worked fine with my Wily install --- my daily-driver workstation is always running mainline kernel --- 4.6 rc1 today --- and daily-build-tracked xubuntu --- keeps life interesting ;-). While it is ... in my opinion ... unfortunate this resource has taken such a hard stance against event *exposing* builds for development OS releases (no one expects them to *support* development enviornments, but would it really be that hard to trigger Launchpad builders to track against development automatically?). Anyway, rants aside: just utilize the relevant sections of the script and call the required commands to ensure you have the requires keys installed your apt sources updated. Basically, all you need is:

**Comment by robfrawley** [comment]
@The-Technicalist I forgot to add that you'll have issues with older node versions. During my time running Xenial the 5.x series for Wily are the only I have used: you may have different luck with 4.x (and likely those before). For clarity:
```bash
curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
echo 'deb https://deb.nodesource.com/node_5.x wily main' | sudo tee /etc/apt/sources.list.d/nodesource.list
sudo apt-get update && sudo apt-get install nodejs
```
Last, ence packages become available for Ubuntu 16.04, you will be able to edit `/etc/apt/sources.list.d/nodesource.list` and replace "wily" with "xenial" followed by simply running `apt-get update && sudo apt-get upgrade`.
---
**If** you run into any package conflicts during this process, which has never happened to me with @chrislea prior PPA or this repo (though it's happened with others too often: I'm looking at you MariaDB and Percona) the following should resolve it:
- Comment out the line in `/etc/apt/sources.list.d/nodesource.list`
- Remove current packages `apt-get remove nodejs nodejs-foo nodejs-bar [...]`)
- Clean/update/upgrade your apt/system `apt-get autoclean ; apt-get clean ; apt-get update ; apt-get upgrade`
- Edit `nodesource.list` again and removed the comment added
- Update your cache and install the "official" Xenial packages `apt-get update ; apt-get install nodejs`

**Comment by mgcrea** [comment]
Ubuntu 16.04 LTS is scheduled to ship tomorrow (Thursday, 21 April). Any news regarding support? Do you intend to provide Snappy packages as well?

**Comment by chrislea** [comment]
Xenial packages are actually already in the repo, but we'll update the
installer scripts once it officially ships. We don't have snappy support
planned at this time.

**Comment by mgcrea** [comment]
http://releases.ubuntu.com/16.04/ 🎉
