### ISSUE TITLE
content-type text/html instead of application/octet-stream on rpm.nodesource.com

### ISSUE THREAD

**Issue by furlongm** [nodesource/distributions#304]
Hi,

It looks like you are serving xml and xml.gz files with a content-type of text/html on rpm.nodesource.com. This breaks rpm repository clients that expect a content-type of application/octet-stream.

I have one particular issue at https://github.com/furlongm/patchman/issues/17#issuecomment-221189471 that is a result of the incorrect content-type. I have not seen this occur before with any rpm repositories. As an example, if you navigate to https://rpm.nodesource.com/pub_5.x/el/7/x86_64/repodata/953321365a5ed6d897a850d16822ed7879d7e0da-primary.xml.gz it will open in the browser, rather than downloading the file (as it should).

Would it be possible to serve e.g. xml and xml.gz files with a content type of application/octet-stream?

This can be done in nginx with e.g.:

        types { application/octet-stream xml gz; }

see http://nginx.org/en/docs/http/ngx_http_core_module.html#types for the full documentation.

Thanks!

**Comment by rvagg** [comment]
I can't find any specific information on the web anywhere about why this would be needed other than clients that might have unreasonably strict expectations. Can you point me to a resource that validates this, or perhaps an official distro tool that has this expectation?

**Comment by furlongm** [comment]
You got me, it's not an official distro tool. :-) However, this is the only repo that this has occurred with in over 6 years of use, with thousands of repos worldwide.

For a resource that validates the issue, RFC7321 says that the sender should generate the correct Content-Type for the payload: https://tools.ietf.org/html/rfc7231#section-3.1.1.5

Anyway, I've modified my client to be more forgiving, so I'll close the issue.

**Comment by rvagg** [comment]
I wasn't looking to "get you", I'm more interested in whether this is an established standard and if so, b what means? I can't find a resource that suggests this is important so I'm hesitant to make changes when it's been working for most people perfectly well to date.

Regarding RFC7231, an .xml file should be `text/xml` if we're going to be strict about it. `application/octet-stream` is traditionally used to force clients to _download_ rather than attempt to render content, this makes sense when the content is for machine rather than human consumption.
