### ISSUE TITLE
Support for Linux Mint 17.3 "Rosa"

### ISSUE THREAD

**Issue by jwsomis** [nodesource/distributions#305]
Using " curl -skL https://deb.nodesource.com/setup_6.x | sudo -E bash -" gives me

## Confirming "trusty" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_6.x/dists/trusty/Release'

## Your distribution, identified as "trusty", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

I recognize 17.3 is not yet listed as being supported, but since it is identifying as trusty shouldn't this be able to install? 
P.s. Using -k to skip cert validation (am behind firewall and certs are huge pain).

**Comment by rvagg** [comment]
Rosa is supported, our script maps it to Trusty, which is why this is failing as "trusty". I think what's going on here is that the script is doing a `curl` of its own and not using your `-k` so failing because of your odd firewall. I recommend that you review https://github.com/nodesource/distributions#debmanual and manually add the repo to your system and identify as "trusty" and it might be OK. The only other problem is that the apt repo's are shared via https so you're going to have to research some apt hackery to allow insecure connections.
