### ISSUE TITLE
Please provide shell script with generic name which always install latest available version of NodeJs

### ISSUE THREAD

**Issue by shivarajnaidu** [nodesource/distributions#318]
I have seen that this ( [https://deb.nodesource.com/setup](https://deb.nodesource.com/setup) ) script installing  Node.js v0.10 on deb based systems.. 
**But the name looks Like More generic .. So have one idea..** 
why not we can provide users, script with generic name [https://deb.nodesource.com/setup](https://deb.nodesource.com/setup) like this, which always installs the latest available version of node js ... Please consider this way ... because it  will be more consistent for naming and providing way to help new people and content writers to point it as default script to install latest version on their machines..

**Comment by chrislea** [comment]
We don't do this because we support multiple active version lines of Node. For example right now, all of 0.10.x, 0.12.x, 4.x, 5.x, and 6.x are still being supported. So we don't want to provide users with a script that could change a major version number (4.x -> 6.x for example) without their knowing.

**Comment by andreineculau** [comment]
FWIW a bash script that does just that could look like

```bash
LATEST_VSN_NODE=9
while true; do
    curl -f -sL https://deb.nodesource.com/setup_$((LATEST_VSN_NODE+1)).x >/dev/null || break
    LATEST_VSN_NODE=$((LATEST_VSN_NODE+1))
done
curl -sL https://deb.nodesource.com/setup_${LATEST_VSN_NODE}.x || bash -
```

PS: while I understand the theory and well-intentions behind saying no to this request, the reality is that it has no supporting argument i.e. people in general run systems that try updating components to the latest major/minor version etc, etc in CI in order to get early warnings that their setup is not fully compatible with upcoming releases. For example on travis you may specify you want the latest node installed, and in some years maybe your code will fail, but at least you will get notified by the default monthly cronjob. Otherwise, you would need to touch all your repos and add/upgrade the nodejs version that is being used on the CI.
