### ISSUE TITLE
Unable to install nodejs with help of yum (Yogesh)

### ISSUE THREAD

**Issue by tikoney** [nodesource/distributions#321]
Facing below issue while nodejs install on 

# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.6 (Santiago)

# curl --silent --location https://rpm.nodesource.com/setup | bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## You don't appear to be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your architecture to be considered for support. Include your 'distribution package' name: sles_es-release-server-6Server-6.6.0.2.1.el6.x86_64.

**Comment by rvagg** [comment]
@tikoney I'm pretty sure "sles_es-release-server-6Server-6.6.0.2.1.el6.x86_64" suggests you're running SUSE Linux Enterprise Server which is not based on Enterprise Linux (RHEL). Even though it uses rpms for installation, we don't provide any support for the various SUSE versions.

**Comment by tikoney** [comment]
The release file not shows it's SLES10 or SLES 11.  it's Red Hat Enterprise Linux Server release 6.6 .

This is a "SLES Expanded Support platform release 6.6".

So will this really cause this issue ?
 /]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.6 (Santiago)
# This is a "SLES Expanded Support platform release 6.6"
# The above "Red Hat Enterprise Linux Server" string is only used to
# keep software compatibility.

**Comment by rvagg** [comment]
OK, I don't know why /etc/redhat-release has that, https://www.suse.com/products/expandedsupport mentions that there may be some RHEL compatibility but without a better understanding of what this beast is I don't think we can change anything on our end.

You could try and manually install it on your system and see if it works. We don't have manual instructions for EL on our README (yet) but you could poke through the script @ https://rpm.nodesource.com/setup_4.x and figure out how it works (sorry, I can't do that off the top of my head). Note that I'm pointing you to the 4.x repository, not v0.10 because v0.10 is going to be deprecated in October, but you can switch to the other script if you want (or the v6 one if you like although it's not LTS yet).

Perhaps an easier alternative would be to just grab an rpm from https://rpm.nodesource.com/pub_4.x/el/6/x86_64/ (replace `4.x` with another Node version if you want) and try installing that. Report back here and let us know if it works or not!
