### ISSUE TITLE
Your distribution, identified as "xenial", is not currently supported

### ISSUE THREAD

**Issue by nonnymoose** [nodesource/distributions#322]
Some software I would like to install is dependent on io.js 2.x.
According to the script, `Your distribution, identified as "xenial", is not currently supported,`.
It's been a while since xenial was released. Could you add support?

**Comment by chrislea** [comment]
Development for iojs was halted before Xenial was released, and iojs is no longer being supported, so we aren't making any new builds for it. We'd *strongly* advise you to move to the Node 4.x series as soon as possible as there have been a number of security vulnerabilities that have been fixed since iojs support ended.
