### ISSUE TITLE
Node v6 => Fedora 24

### ISSUE THREAD

**Issue by I-n-d-e-r** [nodesource/distributions#325]
FEDORA 24

The problem with the installation of Node v6 => NodeSource. I got a message:

```
## Run `yum install -y nodejs` (as root) to install Node.js 6.x and npm.
## You may also need development tools to build native addons:
##   `yum install -y gcc-c++ make`
```

AND => Installed Node v4 from the official repository instead NodeSource.

```
Rozwiązano zależności.
================================================================================
 Package         Arch.           Wersja                   Repoz.          Rozm.
================================================================================
Instalowanie:
 libuv           x86_64          1:1.7.5-2.fc24           fedora           78 k
 nodejs          x86_64          1:4.4.5-1.fc24           fedora          5.9 M

Podsumowanie transakcji
================================================================================
Instalacja  2 pakiety
```

**Comment by callahad** [comment]
Specifically, `dnf install nodejs` incorrectly selects Node 4.x from the Fedora official repositories, instead of using the NodeSource repository.

This is because the Fedora RPM's have a `Epoch: 1`, while the NodeSource RPMs have `Epoch: 0`. The Epoch acts as the [most significant value](http://www.rpm.org/max-rpm-snapshot/s1-rpm-depend-manual-dependencies.html#S3-RPM-DEPEND-VERSION-NOT-ENOUGH) in version comparisons, causing the vendor-supplied packages to appear newer than Fedora's.

__Bumping NodeSource's Epoch to 1 would resolve this.__

**Comment by callahad** [comment]
As a temporary workaround, users can add `exclude=nodejs` to the end of the first stanza in `/etc/yum.repos.d/fedora.repo`

**Comment by chrislea** [comment]
Great catch @callahad, the fix is much appreciated.

I've rebuilt 4.4.6 and 6.6.2 and just verified that installing 6.6.2 on a clean FC24 instance now works as expected. Building 5.x now.

Thanks!
