### ISSUE TITLE
SolydXK Support

### ISSUE THREAD

**Issue by marcdebeer** [nodesource/distributions#332]
Running the following reports that no support is available for SolydXK distribution:

`curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs`

```
## Confirming "solydxk" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_6.x/dists/solydxk/Release'

## Your distribution, identified as "solydxk", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by rvagg** [comment]
Unfortunately we're unable to support the long-tail of Linux distributions ourselves, even if they are based on Debian or Ubuntu.

However, if this distribution is based directly on Debian or Ubuntu and there is a clear mapping of release names then you could add it to our script here: https://github.com/nodesource/distributions/blob/master/deb/src/_setup.sh#L248-L263

That mapping needs to be from what the distro reports from `lsb_release -c -s` to the equivalent Debian or Ubuntu name. Unfortunately your output suggests that it's just saying `solydxk` which suggests that it may not be differentiating between its own versions. e.g. if it's currently based on wheezy but then shifts to jessie at some point, does its `lsb_release -c -s` output change to match that or is it going to continue to say `solydxk`? If so, that's not very helpful and we're likely to get bug reports when things break because of the mismatch.
