### ISSUE TITLE
Your distribution, identified as "yakkety", is not currently supported

### ISSUE THREAD

**Issue by pgrzelka** [nodesource/distributions#335]
When installing 5.x or 6.x on Ubuntu 16.10 "yakkety"

`curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -`
`curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -`

**Comment by rvagg** [comment]
hi @pgrzelka, we intentionally don't support Ubuntu releases until they go gold because so much changes before that happens (particularly this early), so this isn't going to work until late October when Yakkety moves out of Beta. What you can do for now is follow the instructions on the [readme](https://github.com/nodesource/distributions) for Xenial and those packages should work fine for you.
