### ISSUE TITLE
Raspberry Pi Arm6 again...

### ISSUE THREAD

**Issue by dceejay** [nodesource/distributions#337]
Now that node.js org are building an Arm6 binary regularly 

https://nodejs.org/dist/v4.4.7/

could the Debian install script be fixed to detect the architecture and "do the right thing"  and get the Arm6 version for all those Raspberry Pi1 and PiZero users out there ?

**Comment by rvagg** [comment]
Hi @dceejay, unfortunately "doing the right thing" would mean detecting and rejecting an install if armv6 is detected. We only build for armv7 at the moment as that's what's supported upstream by Ubuntu and Debian (etc.) and the various toolchains to make that work (we compile native, rather than reuse binaries from nodejs.org). Raspbian even exists to make this work as Debian never support anything less than armv7.

You're going to have to continue using the binaries from nodejs.org for older Pi's unfortunately.

**Comment by dceejay** [comment]
Ah right...  I didn't realise you guys re-built it. I assumed you would just pull and wrap the existing binaries.
