### ISSUE TITLE
(REQUEST) support for yet another debian distro... Sparky Linux

### ISSUE THREAD

**Issue by Adrianzo** [nodesource/distributions#341]
http://sparkylinux.org/about/ It's "Debian testing based".

PS. It would be nice if we could simply give the argument "--force someDistro" for example, trying to install nodejs. It would save time in some cases.

**Comment by rvagg** [comment]
Hi @Adrianzo, since we don't have the resources to test all of these distros and their variations we have to rely on folks like yourself to provide us with the info we need and to test that it's working. What you need to do is make a pull request to this repo and adjust this file https://github.com/nodesource/distributions/blob/master/deb/src/_setup.sh#L258-L275 adding in a line or two to map Sparky codenames to Debian ones. You can get this by running `lsb_release -c -s` which is what the script uses. The mapping will make the setup script continue on as if you're using the Debain version you added. If it really is *testing* based then `jessie` will probably work. You can test out whether these packages actually work by using the [manual install instructions](https://github.com/nodesource/distributions#debmanual) and adding in `jessie` and the Node version you want.
