### ISSUE TITLE
Updating nodejs debian package reverts npm to v2

### ISSUE THREAD

**Issue by nkovacs** [nodesource/distributions#374]
Every time the nodejs package is updated on my computer, it reverts npm back to v2.
Npm v2 doesn't work with many of my projects, or it works incorrectly.
I usually only notice this when I try to use it and it breaks; then I have to upgrade npm with "sudo npm update -g npm", and hope that npm v2 didn't do too much damage.

You could make a post-install script that checks if npm is already installed, and only overwrite it with the packaged version if it is older.

Another, probably better solution would be to package npm separately, and have an npm2 and npm3 package, with the nodejs package depending on either one of them.

**Comment by chrislea** [comment]
This was a conscious decision we made a while ago. We have to completely remove any previous `npm` installation because if somebody installed a module globally, and the version we are installing changes, it's possible that the global module they had previously installed would cause problems. We're sorry it's inconvenient to have to re-install, but we think this is the best option overall.

Also, keeping `npm` as part of the main `nodejs` package was one of the reasons we started making these packages in the first place, because the majority of people don't want a separate package. If you do want `npm` separately, you may be able to do that by installing everything from directly from your distribution instead of from us.
