### ISSUE TITLE
Your distribution, identified as "yakkety", is not currently supported (from ubuntu 16.10)

### ISSUE THREAD

**Issue by alexfloresf** [nodesource/distributions#391]
I would like to install is  io.js 3.x.
According to the script, Your distribution, identified as "yakkety", is not currently supported,.
It's been a while since yakkety was released. Could you add support?
I installed nodejs7.2.0 without problems :-)

**Comment by chrislea** [comment]
I'm sorry but all versions of io.js are EOL and completely unsupported. We
won't be making any new builds of it going forward. We **strongly** urge
you to move to a supported version of Node on any machines you have running
io.js as there are many security vulnerabilities in all io.js releases
compared to supported Node releases.

__
Sent from phone, please excuse brevity...

On Nov 22, 2016 9:03 PM, "alexfloresf" <notifications@github.com> wrote:

I would like to install is io.js 3.x.
According to the script, Your distribution, identified as "yakkety", is not
currently supported,.
It's been a while since yakkety was released. Could you add support?
I installed nodejs7.2.0 without problems :-)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nodesource/distributions/issues/391>, or mute the thread

**Comment by alexfloresf** [comment]
Thank you very much for the prompt reply, I hope then future news.
Regards.
