### ISSUE TITLE
Remove Node 6.10.1 and revert to 6.10.0

### ISSUE THREAD

**Issue by STRML** [nodesource/distributions#436]
https://github.com/nodejs/node/issues/11977 is a fatal issue affecting 6.10.1 that may crash applications if they upgrade:

```
$ n use 6.10.1                                                                                                                                                                                       
> (42, [...[0], 1]);


#
# Fatal error in , line 0
# unreachable code
#

==== C stack trace ===============================

 1: V8_Fatal
 2: v8::internal::AstNumberingVisitor::VisitSpread(v8::internal::Spread*)
 3: v8::internal::AstNumberingVisitor::VisitArrayLiteral(v8::internal::ArrayLiteral*)
 4: v8::internal::AstNumberingVisitor::VisitRewritableExpression(v8::internal::RewritableExpression*)
...
```

```
$ n use 6.10.0                                                                                                                                                                                       
> (42, [...[0], 1]);
[ 0, 1 ]
```

For safety's sake, it would be prudent to unpublish 6.10.0.

**Comment by chrislea** [comment]
Please believe me when I say I completely understand your concern. However, our policy has always been that if the Node.js foundation pulls a release from the https://nodejs.org site, then we'll do the same. So since they haven't pulled 6.10.1, we aren't pulling out packages either. That said, I fully expect to see 6.10.2 (or something to fix this) out in the near future, and we'll get those packages out just as quickly as we can build them once that lands. Thanks for your understanding.

**Comment by STRML** [comment]
Thanks Chris - and thanks for all your hard work on these distributions.
