### ISSUE TITLE
dpkg-buildpackage

### ISSUE THREAD

**Issue by jjshoe** [nodesource/distributions#439]
Are you using dpkg-buildpackage to build these packages?

Can you share the exact call you're using to turn the xz, dc, and tar.gz into a debian package? looking to change the install location.

**Comment by chrislea** [comment]
We use the `sbuild` suite of things which does, among other things, invoke `dpkg-buildpackage` I believe. A pretty concise rundown can by found by looking at the [Ubuntu Sbuild Quickstart](https://wiki.ubuntu.com/SimpleSbuild). Hope that helps.

**Comment by jjshoe** [comment]
I've been using `debuild -b -uc -us` to rebuild, in case anyone else wants to try.

I'm basically trying to add an installation prefix to node, to have it install to a different version, for testing purposes, turning out to be quite a project.

**Comment by chrislea** [comment]
That's not really the right use case for a `deb` package since those are designed to install system wide, and are not intended to play nicely with multiple versions (ops people aren't keen on having multiple versions of things on a system that could potentially create confusion).

If you want to be able to easily use different versions, I'd recommend checking out [nvm](https://github.com/creationix/nvm).

**Comment by jjshoe** [comment]
We'll have to agree to disagree here, what I'm doing is not far off from many many open source projects.
