### ISSUE TITLE
"wheezy" is not currently supported

### ISSUE THREAD

**Issue by Flynrod** [nodesource/distributions#441]
Fetched 23.5 MB in 7s (3009 kB/s)
Reading package lists... Done

## Installing packages required for setup: apt-transport-https...

+ apt-get install -y apt-transport-https > /dev/null 2>&1

## Confirming "wheezy" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_7.x/dists/wheezy/Release'

## Your distribution, identified as "wheezy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by ibujs** [comment]
NOTE: Debian Wheezy and Ubuntu Precise packages are NOT available for this release. Please reference running Node.js >= 4.x on older distros.
That's why you should read the README :stuck_out_tongue: 
The latest version for wheezy is Node 6.x, see
[https://github.com/nodesource/distributions/blob/master/OLDER_DISTROS.md](https://github.com/nodesource/distributions/blob/master/OLDER_DISTROS.md)
Newer than 6.x will not be available for said reasons.

**Comment by chrislea** [comment]
Thanks @ibujs. As he said, Node.js >= 7.x is not available on Debian Wheezy or Ubuntu Precise.
