### ISSUE TITLE
Node.js latest on Debian Wheezy

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [nodesource/distributions#455]
Hi!

I was trying to get node 7 on an older Debian Wheezy server to debug some performance issues we're having moving to a new Ubuntu 16.04 server with node 7.6.

The repos are broken, and there's a [documentation entry](https://github.com/nodesource/distributions/blob/master/OLDER_DISTROS.md) stating that newer versions won't work on Wheezy due to old compilers and whatnot.

I then stumbled across the Docker node images and noticed a v.7.9.0 image based on wheezy. I pulled out some links from the [Dockerfile](https://raw.githubusercontent.com/nodejs/docker-node/e1103db1e7330f620ec4b5961b93936da11becdf/7.9/wheezy/Dockerfile), downloaded the tarball and just replaced `/usr/lib/node_modules` and `/usr/local/bin/nodejs` with the goodies extracted from it.

They work just fine! I don't know if it's a super bad practice or something, but if it's just a documentation flaw, you might want to update it :)

Cheers!

**Comment by chrislea** [comment]
The situation is a bit complex. Currently, we _can_ compile 7.x for Wheezy, but the expectation is that at some point during the 7.x or 8.x release lines, the version of V8 will bump up to a point where we won't be able to compile it any longer for Wheezy (or Ubuntu Precise). So we decided to not make those builds since we felt that saying "sorry this is too old" out of the gate would be better than having to stop supporting a release somewhere in the middle of its lifetime. Hope this sheds some light on the situation.
