### ISSUE TITLE
Installation fails silently and returns 0

### ISSUE THREAD

**Issue by gibfahn** [nodesource/distributions#477]
Moved from https://github.com/nodejs/nodejs.org/issues/1220, raised by @haanjde

---

* **URL**: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
* **Operating system**: Debian 8.7.1 Jessie

When the `curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -` command fails by being unable to reach a DNS server, it fails silently and with a returncode of 0.

Please correct this or put a warning in place.

**Comment by farvardin** [comment]
if you have some old apt repositories and they don't work anymore, the installer will fail. A workaround is to edit the script and remove the "exit 1" at this part:

bail() {
    echo 'Error executing command, exiting'

Why don't use a PPA like before? This shouldn't happen in this case.

**Comment by chrislea** [comment]
@gibfahn If the command fails because of a problem with a DNS lookup, that's not in our control to fix. You should check with your ISP and make sure their name servers are working properly. We haven't seen any indication that our repositories aren't behaving normally.

@farvardin We don't have any "old apt repositories" anywhere, only our current repos at deb.nodesource.com and rpm.nodesource.com. I assume that when you ask why we're not using a PPA anymore, you want to know why we're not using Launchpad.net to distribute packages. The answer is that Launchpad only works for Ubuntu releases. By setting up our own repositories we are able to support Ubuntu, Debian, Red Hat, CentOS, Fedora, and others.

Hope this helps.
