### ISSUE TITLE
Support for Debian 9 Stretch

### ISSUE THREAD

**Issue by pc-jedi** [nodesource/distributions#480]
As Debian 9 Stretch is now stable, it should be supported by nodesource.

**Comment by chrislea** [comment]
We are well aware. All future builds of any Node.js releases will support Stretch, and we may back-build the last released things depending on demand. Thanks for your interest!

**Comment by 2mf** [comment]
@chrislea, Why is that ticket already closed.
There are currently no dists for strectch available in
https://deb.nodesource.com/node_7.x/dists
and
https://deb.nodesource.com/node_8.x/dists

**Comment by mmoll** [comment]
We do have demand for 6.x on stretch to get http://projects.theforeman.org/issues/19512 going

**Comment by chrislea** [comment]
@2mf The ticket is closed because the question has been answered. There haven't been any new Node.js releases since Stretch was released. As soon as there is a new version of Node.js out, we'll build it for Stretch.

@mmoll we may back-build 6.x for stretch depending on demand, but until then you can always use the binaries published by the actual Node.js foundation instead. They should work fine.

**Comment by mmoll** [comment]
@chrislea not entirely, if one does have a build and packaging infrastructure in place that wants to pull in everything via apt repos ;)

**Comment by chrislea** [comment]
Okay folks, I've built the most recent versions of 6.x and 8.x for Debian Stretch and pushed them to the repos. You should be able to install as per normal now.

https://twitter.com/chrislea/status/877704482481516544

**Comment by mmoll** [comment]
Thanks @chrislea, working fine!
