### ISSUE TITLE
node 4.x no longer supported on stretch?

### ISSUE THREAD

**Issue by frankh** [nodesource/distributions#481]
Suddenly my docker builds are failing as node 4.x is no longer supported on stretch

Is there a reason for this?

**Comment by frankh** [comment]
I see there's been some discussion on this, and it was never officially support before. However, it used to work and now it doesn't, which is very frustrating

**Comment by chrislea** [comment]
We didn't back-build 4.x for stretch because it's already included in the main stretch distro. Also, 4.x is in maintenance mode and you should _really_ be updating to 6.x ASAP.

That all said, we don't want to break anybody's build systems, so I've gone ahead and built the most recent 4.x for stretch, and those builds are available now. So things should start working again.
