### ISSUE TITLE
Support: Fedora 27

### ISSUE THREAD

**Issue by lig** [nodesource/distributions#566]
Fedora 27 is final. There is still no repo for it.

Also, it would be nice to prepare the repo a bit before Fedora or any other distro goes final to simplify the upgrade routine for early adopters.

FYI:
* There was an issue on this earlier https://github.com/nodesource/distributions/issues/542
* There were discussions on the same topic regarding the Docker CE Fedora repo here https://github.com/docker/for-linux/issues/143 and https://github.com/docker/for-linux/issues/35. Consider noticing feedback provided for each commit via emojis. This should make an impression of what the community thinks is a right approach.

**Comment by chrislea** [comment]
Fedora 27 has been supported since the day it was released. You can see the package files for 9.x here:

https://rpm.nodesource.com/pub_9.x/fc/27/x86_64/

There aren't any 8.x packages yet because there haven't been any 8.x releases since FC27 shipped. When the next 8.x release comes out, it will be published for FC27.

Our policy has always been that we don't support new distributions until they are at the final release schedule. We sometimes publish Ubuntu releases a little early depending on demand. This is more problematic with Fedora though because they tend to not stick to their release schedules very strictly, so we can get into a situation where we're supporting a beta release for longer than we want to. This may also change in the future depending on demand.

Hope this helps.

**Comment by lig** [comment]
I've been using 8.x repo. Now I've got this. The same insanely uncomfortable for users release policy everywhere I guess. Why make the repo if it doesn't exist always?
