### ISSUE TITLE
Debian packages should have LTS/Current alternatives

### ISSUE THREAD

**Issue by coladict** [nodesource/distributions#578]
In addition to having `https://deb.nodesource.com/node_8.x` and `https://deb.nodesource.com/node_6.x`, you should have a `https://deb.nodesource.com/node_lts` that is a soft-link to whichever the current LTS is major version is when moved.

Same with current should have a `https://deb.nodesource.com/node_current` link pointing to `https://deb.nodesource.com/node_9.x` or wherever, after it changes.

This is much the same way as seen in http://ftp.uk.debian.org/debian/ where they change the `stable`, `unstable`, `oldstable` links around every major update, while still keeping the explicit version urls, like `jessie` and `wheezy`.

**Comment by 2E0PGS** [comment]
+1 for this.

**Comment by chrislea** [comment]
Thanks for the input. I understand the request, but we made a decision a long time ago to **never**, under any circumstances, update through major Node versions automatically without any sort of user intervention. Which is why we haven't already done something like this. If there is sufficient demand we may look at it again in the future.
