### ISSUE TITLE
No debuginfo for Node 9.x 

### ISSUE THREAD

**Issue by oraoto** [nodesource/distributions#579]
Unlike older version, currently no debuginfo are provided for Node 9.x:

https://rpm.nodesource.com/pub_9.x/el/7/x86_64/
https://deb.nodesource.com/node_9.x/pool/main/n/nodejs/

Any plan to add them back?

**Comment by hemooo979** [comment]
Any plan to add them back?

**Comment by chrislea** [comment]
That's because around when 8.4.0 was release, we stopped building Node from sources and are now just taking the binary tarballs from https://nodejs.org/dist/ and re-packaging those into `deb` and `rpm` formats. Since they don't have debug builds, we no longer have the debug packages. We don't have any plans to add them back because to do so, we'd have to start building everything from source again which causes its own headaches. Hope this helps!
