### ISSUE TITLE
Your distribution, identified as "fedora-release-22-1.noarch", is not currently supported

### ISSUE THREAD

**Issue by ramdon90** [nodesource/distributions#582]

**Comment by chrislea** [comment]
Fedora 22 has been EOL for some time now and is no longer supported upstream. Therefore we no longer make any packages for it. If you update to a supported version of Fedora, you'll find we have supported packages.

**Comment by schester44** [comment]
@chrislea Is it possible to install an older package on Fedora? My employer is using 13. Having trouble finding a suitable installation method.

**Comment by chrislea** [comment]
@schester44  Fedora 13 has been EOL since 2011 according to [this](https://fedoraproject.org/wiki/End_of_life), so if your employer is running it, I'd say you have **much** larger issues on your hands than being able to install Node. I honestly have no idea if it will install on a system that old, as I suspect the version of `libstdc++` is too ancient to support a modern version of V8.

Update to a supported distribution. Immediately. For real.
