### ISSUE TITLE
Cannnot install v8 on Ubuntu 16.04

### ISSUE THREAD

**Issue by HenryMehta** [nodesource/distributions#594]
I'm trying to install Node.js v8.x: on a Ubuntu 16.04 LTS (Xenial Xerus) using `curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -` but I'm getting the following errors.

> E: Failed to fetch http://ppa.launchpad.net/kirillshkrogalev/ffmpeg-next/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
> E: Some index files failed to download. They have been ignored, or old ones used instead.

I'm cannot find anyone with a similar issue so cannot work out how to sort.

**Comment by chrislea** [comment]
The problem is that you've enabled a PPA from Launchpad that's not working for you. Specifically [this one](https://launchpad.net/~kirillshkrogalev/+archive/ubuntu/ffmpeg-next). We don't have any control over that PPA so we can't fix it. If you get that fixed, our setup script should run correctly and set up our repository.
