### ISSUE TITLE
setup_9.x seems broken

### ISSUE THREAD

**Issue by satacm** [nodesource/distributions#596]
From the "Install" page of nodesource:
(Running on Linux Mint - Rebecca

`# curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -`

But this command fails with: three errors:
- W: Failed to fetch https://deb.nodesource.com/node_9.x/dists/trusty/main/source/Sources Received HTTP code 403 from proxy after CONNECT
- W: Failed to fetch https://deb.nodesource.com/node_9.x/dists/trusty/main/binary-amd64/Packages Received HTTP code 403 from proxy after CONNECT
- W: Failed to fetch https://deb.nodesource.com/node_9.x/dists/trusty/main/binary-i386/Packages Received HTTP code 403 from proxy after CONNECT
E: Some index files failed to download. They have been ignored, or old ones used instead.
Error executing command, exiting

Going to those URLs and to me it seems that the targets are not correct:
- https://deb.nodesource.com/node_9.x/dists/trusty/main/source/ `Sources` is now `Sources.gz`
- https://deb.nodesource.com/node_9.x/dists/trusty/main/binary-amd64/ `Packages` is now `Packages.gz`
- https://deb.nodesource.com/node_9.x/dists/trusty/main/binary-i386/ `Packages` is now `Packages.gz` and replaced with a build(?) text file, `Packages`

**Comment by chrislea** [comment]
Hrm. I'm not sure what's going on with your client. The standard behavior for `apt` is to look for the gzipped versions of all of those, which is why this error is happening. The `.gz` versions are there as they should be, but for some reason your client is not looking for the gzipped versions.

This isn't specific to the 9.x repo, if you look at the repositories for any of the other versions you'll see the same thing, meaning that the gzipped versions of those files will be there and that's it.

Are you behind some sort of network proxy that may be rewriting these filenames or anything?

**Comment by satacm** [comment]
Thanks Chris That was the problem.  Not a network proxy, but an apt proxy/cacher.
This particular client had "apt-cacher" installed, and this was failing to pickup those packages from deb.nodesource.com.  I had that client directly access packages from their original source, (not the cacher) and the node.js packae.
