### ISSUE TITLE
No Support for armv71 architecture (raspberry Pi 2)

### ISSUE THREAD

**Issue by tyjsoft** [nodesource/distributions#600]
Since RP2 is such an accessible platform, it would be great if it was supported from the repo.  

Details: Running CentOS 7 on Rapsberry Pi 2

# curl -sL https://rpm.nodesource.com/setup_8.x | bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

**Comment by chrislea** [comment]
We actually do support `armv7`, but only for the `deb` packages we make. Getting the build toolchain that we'd need to make RPM packages set up is quite complicated as it turns out, and we just haven't seen the amount of demand for RPM packages that we'd need to justify the effort (this is the first inquiry we've gotten).

If you use a Debian based OS on your RPi2 (Debian Jessie or newer, Ubuntu Trusty or newer, Raspbian, etc), then you'll find supported `deb` packages. Hope this helps.
