### ISSUE TITLE
No Nodejs Source packages for 6.x

### ISSUE THREAD

**Issue by dasuxullebt** [nodesource/distributions#604]
Hello. In the repositories for 6.x, there are no source packages for nodejs, even though there is a source repository, which seems to be empty however.

**Comment by chrislea** [comment]
There aren't source packages for anything newer than (I think) 6.11.1 because at that point, we stopped compiling from source for every distro / architecture that we support. We are now just packaging up the binaries that are produced by the Node Foundation into `deb` and `rpm` formats for consistency. Hope this helps.

**Comment by dasuxullebt** [comment]
Would it be possible to add support for armv6 (raspbian on older raspberry pies)? As far as I see there are binary tarballs for that.

**Comment by chrislea** [comment]
We haven't made `armel` packages because getting the toolchain needed to build them in place is a fair amount of work and also the major distros seem to be moving away from supporting it. If there's sufficient demand we'll look into it, but to date that hasn't been the case (you're the second person to ask about it). Hope this helps.

**Comment by joakim** [comment]
Here's a 3rd person asking for it, if that helps…
