### ISSUE TITLE
Incorrest version of node getting installed for setup_10.x

### ISSUE THREAD

**Issue by sudoor** [nodesource/distributions#680]
When I use `curl -sL https://rpm.nodesource.com/setup_10.x | bash -` to install node `v10`,
but I use `node -v` got  `node 0.10`.

**Comment by chrislea** [comment]
What distribution and version are you trying to install onto? Also, what is the output of:
```
% which node
```

**Comment by vanessayuenn** [comment]
I am having the same issue when trying to install node 10 onto a docker image based off of `i386/ubuntu:trusty`.

**Comment by chrislea** [comment]
We don't package Node 10.x for Trusty due to the lack of compilers new enough to build V8 for that target. If you update to a newer supported Ubuntu release, you'll find 10.x is supported.

**Comment by vanessayuenn** [comment]
In that case, this message from the log is extremely confusing:
```
## Confirming "trusty" is supported...
```

**Comment by chrislea** [comment]
The setup script works (roughly) by first figuring out what distribution you have, then seeing if there are any packages for that distribution.

I also just re-looked here and you're trying to install 10.x onto an `i386` machine. The node foundation isn't making 32bit Intel builds anymore starting at 10.x, so you'd need to update to a newer distro and use an `amd64` image to get working packages.

I'm sorry, as I understand this is inconvenient. Unfortunately, supporting new versions of Node on old distros is often somewhere between "too much work to be worth it" and "not actually possible" due to the compiler requirements.
