### ISSUE TITLE
node_4.x on Bionic/18.04 missing

### ISSUE THREAD

**Issue by jrnewell** [nodesource/distributions#711]
I don't see a 4.x build for Ubuntu 18.04 bionic in https://deb.nodesource.com/node_4.x/dists/

I assume I can just use artful (or nvm) and be OK, but it would be nice to have.

**Comment by chrislea** [comment]
4.x was EOL before Bionic was released. Additionally, Bionic ships with 8.x, so `apt` wouldn't get 4.x from our repository be default anyway. So for these reasons we don't make packages for that target. We **strongly** recommend that you **DO NOT** use a 4.x release. They aren't getting security updates anymore, and several known vulnerabilities have been patched since the last 4.x release came out.
