### ISSUE TITLE
node_10.x xenial i386 packages file empty

### ISSUE THREAD

**Issue by msbit** [nodesource/distributions#715]
I was just installing nodejs on my machine and was wondering why I kept on getting the Ubuntu nodejs `4.2.6~dfsg-1ubuntu4.2`.

It looked like the `InRelease` file was being properly downloaded, but then none of the `Packages` files were being downloaded.

I traced this back to `https://deb.nodesource.com/node_10.x/dists/xenial/main/binary-i386/Packages` and `https://deb.nodesource.com/node_10.x/dists/xenial/main/binary-i386/Packages.gz` being empty.

If this isn't the right place for this issue, let me know.

**Comment by chrislea** [comment]
The issue you're running into is that the Node foundation isn't making 32bit Intel builds for 10.x and newer anymore. If you try to install 8.x, or if you switch to a 64bit Xenial install, you'll find supported packages. Hope this helps!

**Comment by msbit** [comment]
@chrislea ah, yep that makes sense!

Might be worth thinking about making the installer for 10.x check for supported architectures in addition to distros.

For my purposes, I was able to get 10.x up and running on my machine through `snap`.

**Comment by chrislea** [comment]
Updating the installers is on the TODO, but this doesn't come up too much so it's not a high priority at the moment. Also because right now all of the installer scripts are generated from a common set of sources, and as soon as we start adding "if distro X with arch Y then Node Z" logic, that all gets a lot more complex.

Thanks for the input all the same. :)
