### ISSUE TITLE
Unable to install node 8 on CentOS 5.8

### ISSUE THREAD

**Issue by dparasam** [nodesource/distributions#717]
From the [documentation](https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora) page, I see CentOS 5 is listed as a supported platform, whereas when I try to install nodejs on it, I get an error:
```
# cat /etc/redhat-release
CentOS release 5.8 (Final)
#  curl --silent --location http://rpm.nodesource.com/setup_8.x | sudo bash -

## Installing the NodeSource Node.js 8.x LTS Carbon repo...


## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el5-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_8.x/el/5/x86_64/nodesource-release-el5-1.noarch.rpm'

## Your distribution, identified as "centos-release-5-8.el5.centos", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

**Comment by chrislea** [comment]
Sorry, that page is outdated. I'll ping somebody about fixing it. CentOS5 isn't supported for Node versions newer than 4.x (which itself is no longer supported) due to the fact that we can't compile modern versions of V8 using compilers and `libstdc++` that are as old as what's on CentOS5. If you update to CenOS 6.x or 7.x you'll find supported packages.

**Comment by dparasam** [comment]
Thanks.
