### ISSUE TITLE
Add support for upcoming Ubuntu 15.04 release. 

### ISSUE THREAD

**Issue by Nikki1993** [nodesource/distributions#74]
We are a little over month away from the official release and git repo already has Vivid support. Would be nice if you could add support for Vivid release too.

**Comment by rvagg** [comment]
To repeat and adjust the same words I ued in #13 for Utopic:

We won't be officially supporting Vivid until it's released by Canonical, towards the end of April. In the meantime, the Utopic binaries should work fine, simply run this as **root** to try it out with Node.js v0.10:

```text
apt-get update && apt-get install curl apt-transport-https -y
curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
echo 'deb https://deb.nodesource.com/node_0.10 utopic main' > /etc/apt/sources.list.d/nodesource.list
echo 'deb-src https://deb.nodesource.com/node_0.10 utopic main' >> /etc/apt/sources.list.d/nodesource.list
apt-get update && apt-get install nodejs -y
node -v && npm -v
```

For Node.js v0.12, the /etc/apt/sources.list.d/nodesource.list entries in the above commands should be:

```
deb https://deb.nodesource.com/node_0.12 utopic main
deb-src https://deb.nodesource.com/node_0.12 utopic main
```

For io.js v1.x, the /etc/apt/sources.list.d/nodesource.list entries in the above commands should be:

```
deb https://deb.nodesource.com/iojs_1.x utopic main
deb-src https://deb.nodesource.com/iojs_1.x utopic main
```

and you will also want to install `iojs` otherwise you'll get the default Ubuntu binaries:

```
apt-get update && apt-get install iojs -y
```

Additionally, if you want to support building native add-ons:

```text
apt-get install build-essential python -y
```

Optionally, to confirm a full, working installation:

```text
curl -sL https://deb.nodesource.com/test | bash -
```

**Comment by ronthepanda** [comment]
@rvagg works perfect for me on Ubuntu 15.04. Thanks

**Comment by rvagg** [comment]
should be working via the standard means now since it's officially been released
