### ISSUE TITLE
setup_10.x script installs 10.1 instead of 10.13 on Ubuntu 14.04

### ISSUE THREAD

**Issue by jacknagel** [nodesource/distributions#749]
On a clean Ubuntu 14.04/amd64 machine, the following installs Node 10.1:
```
$ curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
$ sudo apt-get install -y nodejs
$ node -v
v10.1.0
```

I expected it to install 10.13 (or at least something more recent than 10.1).

I don't know anything about apt repositories, but it looks like https://deb.nodesource.com/node_10.x/dists/trusty/main/binary-amd64/Packages is outdated?

**Comment by chrislea** [comment]
The reason is that at that release, they adopted a version of V8 that's too new to be compiled on 14.04. We note that Trusty isn't supported for 10.x and newer on [the distributions page](https://github.com/nodesource/distributions/#deb). If you update to a newer supported version of Ubuntu such as Xenial or Cosmic, you'll find supported packages. Hope this helps.
