### ISSUE TITLE
## Your distribution, identified as "", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

### ISSUE THREAD

**Issue by adamwilbert** [nodesource/distributions#760]
Attempting install in a docker container (from the base python debian image)

When I run `curl -sL https://deb.nodesource.com/setup_10.x | bash -`

I get ## Your distribution, identified as "", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

and am unable to install a new version of node.js

Thoughts?

**Comment by chrislea** [comment]
I'm not sure since I don't know what your Docker environment looks like, but if `lsb_release` doesn't return anything, then the setup scripts won't work. I'd recommend looking at the [manual installation instructions](https://github.com/nodesource/distributions/#debmanual) and set the repository up that way. Hope this helps!
