### ISSUE TITLE
Your distribution, identified as "centos-release-6-6.el6.centos.12.2.i686", is not currently supported

### ISSUE THREAD

**Issue by arifabbass** [nodesource/distributions#770]
Your distribution, identified as "centos-release-6-6.el6.centos.12.2.i686", is not currently supported

**Comment by chrislea** [comment]
We don't support 32bit builds for any of the current release lines on CentOS 6. This is either due to not having compilers that can build a modern V8 on a 32bit CentOS 6 system (in the case of Node 8.x), or due to the Node foundation simply not making 32 bit builds for Node versions newer than 8.x. If you use a 64bit system, you'll find supported packages. Hope this helps.
