### ISSUE TITLE
Node 11 packages directory is empty for ubuntu 16.04 32-bit

### ISSUE THREAD

**Issue by usaar33** [nodesource/distributions#784]
See https://deb.nodesource.com/node_11.x/dists/xenial/main/binary-i386/

This means that nodesource_setup.sh will pass with no warnings (it successfully adds the PPA), but apt install nodejs will install distribution default.

Either the package should exist or this link should 404.

**Comment by chrislea** [comment]
I understand what you're saying, but it's not best practice for a repo to return a 404 if it's functioning properly. And "not having any packages for the target machine" doesn't necessarily mean that a repo isn't working correctly. Because if it does return a 404, `apt` will just stop working altogether, which isn't what people actually want. This is why Canonical tells people to just [disable repos that are returning a 404](https://askubuntu.com/questions/65911/how-can-i-fix-a-404-error-when-using-a-ppa-or-updating-my-package-lists).

The reason there aren't any packages for you, in this case, is that the Node foundation stopped making 32bit Intel builds at version 10.x. If you install 8.x, or if you update to a 64bit machine, you'll find supported packages. Hope this helps.

**Comment by usaar33** [comment]
It's best practice to produce a loud failure than a soft failure.  The problem is not that the packages don't exist (I understand node can't support 32 bit operating systems forever); the problem is that nowhere in the process does the user receive any sort of error.  Following the instructions, the user silently installs the wrong version of node (4.x!) which is much worse than seeing that something went wrong.

In face, nodesource_setup.sh even incorrectly tells the user all is working well:
```
## Confirming "xenial" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_11.x/dists/xenial/Release'
...
## Run `sudo apt-get install -y nodejs` to install Node.js 11.x and npm
```

Note that the nodesoruce_setup.sh error handling is much better when it detects a version is not supported:

```
## Confirming "xenial" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_12.x/dists/xenial/Release'

## Your distribution, identified as "xenial", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

Anyway, I don't want to be prescriptive in what *should* happen, but the point is that the setup script should error, not silently pass. Whether that's making the repo 404 (which I feel is fine since it immediately tells the user something is wrong with the node PPM) or special error handling in the script is your call
