### ISSUE TITLE
nodejs 6.11.4

### ISSUE THREAD

**Issue by torrealba2719** [nodesource/distributions#786]
I tried to install nodejs in its latest version .. but only installs 6.11.4 my Linux distribution is Lubuntu 17.04 lts   

> ng run app:serve --host=0.0.0.0 --port=8100
[ng] You are running version v6.11.4 of Node.js, which is not supported by Angular CLI v6.
[ng] The official Node.js version that is supported is 8.9 and greater.
[ng] Please visit https://nodejs.org/en/ to find instructions on how to update Node.js.

[ERROR] ng has unexpectedly closed (exit code 3).
        
        The Ionic CLI will exit. Please check any output above for error 
        details.

**Comment by chrislea** [comment]
Please post the full output of the installer script so we can try to see what's going on. Also, the outputs of the commands:
```
% apt-cache policy nodejs
% which $(nodejs)
% lsb_release -a
% uname -a
```
would be helpful.

**Comment by rwky** [comment]
I'm getting a similar issue on Ubuntu 18.04 it appears the Packages file isn't being updated

https://deb.nodesource.com/node_6.x/dists/bionic/main/binary-amd64/Packages in this case it's pinned at `Version: 6.14.1-1nodesource1`

I've had a quick check of the other apt repos for the currently releases still supported by distros and Debian sid https://deb.nodesource.com/node_6.x/dists/sid/main/binary-amd64/Packages and debian Buster https://deb.nodesource.com/node_6.x/dists/buster/main/binary-amd64/Packages are also out of date

Installation log attached, note I had to pin the repo with
```
Package: *
Pin: origin deb.nodesource.com
Pin-Priority: 600
```
[install.log](https://github.com/nodesource/distributions/files/2916225/install.log)

Since there are some security releases out it would be great if this can be fixed ASAP, let me know if you need anymore info.
