### ISSUE TITLE
Latest CentOS 7.6 not supported?

### ISSUE THREAD

**Issue by karezza** [nodesource/distributions#810]
Clean install of latest CentOS from DVD.  Configured HTTP_PROXY and HTTPS_PROXY.  Then:

# curl -ksL https://rpm.nodesource.com/setup_10.x | bash -

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Your distribution, identified as "centos-release-7-6.1810.2.el7.centos.x86_64", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support

**Comment by oslater** [comment]
From your description it looks like you're behind a proxy and this issue is related with your proxy setup. You can verify that by just running the curl command on the command line:

`curl -Lf -o /dev/null 'https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'`

Note that I removed `-s` (--silent option) so you can see the output from the curl command.

Alternatively, you can download the RPM file from the URL ('https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm') and install it yourself. This will create the repo file `/etc/yum.repos.d/nodesource-el7.repo` and then you can just run `sudo yum install nodejs`
