### ISSUE TITLE
yarnpkg not linked when installing snap

### ISSUE THREAD

**Issue by stealthybox** [nodesource/distributions#816]
The `yarnpkg` command is necessary for avoiding collisions with Hadoop tooling.
It should be linked into the PATH for any valid `yarn` installation. [(ref)](https://github.com/yarnpkg/yarn/issues/673#issuecomment-254004512)

The snap includes `yarnpkg`, but does not include a command wrapper or link in `/snap/bin`:
```
❯ ls /snap/node/1816/bin/
node  npm  npx  yarn  yarn.cmd  yarn.js  yarnpkg  yarnpkg.cmd

❯ ls /snap/node/1816/ | grep command
command-node.wrapper
command-npm.wrapper
command-npx.wrapper
command-yarn.wrapper

❯ which yarn yarnpkg
/snap/bin/yarn
yarnpkg not found
```

We should fix the snap so that it links the supplied `yarnpkg` for the user.

related: https://github.com/gobuffalo/buffalo/issues/1635

**Comment by rvagg** [comment]
This one's tricky because we need to apply to the snap store for automatically published aliases where the name is not the name of the snap (`npm`, `npx` and `yarn` had to go through this process).

As a workaround, run: `sudo snap alias node.yarn yarnpkg` and you'll get what you need. If you want to document that in the README here then that would be welcome, via a PR, I think.

If you want it to be officially pushed from the snap store then I'd encourage that too: https://docs.snapcraft.io/process-for-aliases-auto-connections-and-tracks/455 - feel free to start that process, ping me, reference this issue if they take objection to the fact that you're not the author. If they approve (be patient), I'll help get it published (in https://github.com/nodesource/distributions/blob/master/snap/snapcraft.yaml.sh and the repo where it's actually run from).

(this issue can be closed I think)

**Comment by stealthybox** [comment]
@rvagg thanks for the workaround -- I've created the topic:
https://forum.snapcraft.io/t/requesting-yarnpkg-command-alias-for-node-snap/10868

**Comment by rvagg** [comment]
This is live now, `yarnpkg` should be available for fresh snap installs of `node`. My experience in the past is that you have to reinstall to get all new aliases of a snap, they don't just appear. So either add the alias manually as above or `sudo snap remove node` and `sudo snap install node --channel=12 --classic` and `yarnpkg` should work.

(@gkrizek this issue can be closed now)

**Comment by gkrizek** [comment]
Thanks @rvagg !
