### ISSUE TITLE
Mirror server

### ISSUE THREAD

**Issue by mchen6** [nodesource/distributions#818]
Dear nodesource maintainers,

We use nodesource regularly and it works great. However under many occasions the install script was stalled due to slow network. Is there a solution for mirror servers to speed up the download?

**Comment by gkrizek** [comment]
We serve these files from a global CloudFront distribution so I doubt retrieving the scripts is the issue. Rather, I'd bet it's slowness somewhere inside the script, like running `apt update`. Could you post the output of an install and indicate where you see slowness? Thanks!

**Comment by mchen6** [comment]
Thanks for your notice! Please see below screenshots. In most cases it stalled here when downloading the node package.

![1](https://user-images.githubusercontent.com/1168741/55060298-1f39f600-50ac-11e9-9d33-d96e8322f85a.png)
![2](https://user-images.githubusercontent.com/1168741/55060302-23feaa00-50ac-11e9-865b-e34e2929303e.png)

**Comment by gkrizek** [comment]
Strange. Do you experience network problems with other services on this server? Could you give me your rough geographical location?

Like I said, we use CloudFront for these so I can't imagine you'd be getting a 2.7 Kb/s download from one of their edge locations.

**Comment by mchen6** [comment]
We are located in Shanghai, China. We haven't tried other services on this server. If you have a test url we can report the information to you.

**Comment by pablodgonzalez** [comment]
In Argentina same problems.

**Comment by zypA13510** [comment]
@mchen6 There seems to be an (unofficial) mirror at Tsinghua Tuna: https://mirrors.tuna.tsinghua.edu.cn/nodesource/

@gkrizek CloudFront (and some other CDNs) are believed to be semi-censored in China, the connection is usually slow or periodically blocked.

**Comment by zypA13510** [comment]
Coming back to this years later, I noticed that a lot of unofficial mirrors in China stopped serving nodesource, citing some "upstream issues"<sup>[[1]]</sup>.

@JungMinu @gkrizek does anyone know what the actual issue is?

As much as I hate censorship, there is nothing we can do about it. It's painfully slow to download from nodesource, as shown by mchen6 above. It would be very kind of you to work with these mirror providers to sort out any issues, would you please?

[1]: https://mirrors.tuna.tsinghua.edu.cn/news/#remove-nodesource
