### ISSUE TITLE
GPG key for RPM packages

### ISSUE THREAD

**Issue by n3ph** [nodesource/distributions#824]
Request to reopen https://github.com/nodesource/distributions/issues/366

**Comment by rjhornsby** [comment]
Without any support from the devs, the only way I can see around this problem is to extract the key from the RPM, and embed it into our cookbooks, (whatever puppet calls their thing), etc. That's a terrible work around.

As an aside, I wasted about 20 minutes searching the interwebs for a URL that pointed at the gpg key, figuring *I* was just missing it. Ahh, #366. so ... it's very confusing, but not publishing the key accessible via a URL like the packages is ... intentional?

**Comment by nqb** [comment]
@chrislea, any chance to have #366 reopened ?

**Comment by andrew-niaid** [comment]
It appears to be here in the old 0.10 repo. https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL

Unless you are using the nodesource-release package from pub_10.x (the v10 LTS repo), which appears to be signed with a completely different key (Key ID 2f59b5f99b1be0b4). This is neither the RPM key nor the Apt key. It has accidentally been used before if you look at closed issues.

**Comment by nqb** [comment]
Thanks @andrew-niaid !

**Comment by nqb** [comment]
Hello,

See #989

**Comment by discoltk** [comment]
Over a year later and still not fixed.   Classy.

**Comment by n3ph** [comment]
SecOps is hard... Let's go shopping...
