### ISSUE TITLE
Add Provides for RPMs

### ISSUE THREAD

**Issue by fuero** [nodesource/distributions#855]
As EPEL contains an npm package and existing RPMs relying on that fact break,
I suggest adding lines like these to the SPEC files:

```
Provides: npm = 6.8.0
Provides: /usr/bin/npm
```

**Comment by mikecavalieri** [comment]
I think it might need to be something closer to:
Obsoletes: npm
Provides: npm
Conflicts npm

We need the package manager to know that the npm rpm should be removed when this version of nodejs is installed.  This version of nodejs includes npm instead of it being a separate package like the EPEL version.

**Comment by igsu** [comment]
As stated by @mikecavalieri, this version of Node.js includes `npm`. It's not a separate package like in the EPEL version.
