### ISSUE TITLE
Failed to install on Ubuntu 14.04 `trusty`

### ISSUE THREAD

**Issue by LinusU** [nodesource/distributions#9]
```text
Preparing to unpack .../nodejs_0.10.31-1chl1~trusty1_amd64.deb ...
Unpacking nodejs (0.10.31-1chl1~trusty1) over (0.10.25~dfsg2-2ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/nodejs_0.10.31-1chl1~trusty1_amd64.deb (--unpack):
 trying to overwrite '/usr/share/man/man1/node.1.gz', which is also in package nodejs-legacy 0.10.25~dfsg2-2ubuntu1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Processing triggers for man-db (2.6.7.1-1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_0.10.31-1chl1~trusty1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

`nodejs-legacy` provides a symlink from `/usr/bin/node` to `/usr/bin/nodejs` which is very helpful if you are used to Node.js being installed as `node`.

I think that the correct solution is to mark this package as conflicting with `nodejs-legacy` and, if nodesource is providing the symlink, mark it as replacing.

**Comment by rvagg** [comment]
`sudo -E` is now on the readme

**Comment by n0mer** [comment]
for me - the underlying problem was the following:

root@669a56e7c4c4:/# curl -Lf https://deb.nodesource.com/node_0.12/dists/trusty/Release
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
