### ISSUE TITLE
Node 12 LTS on Ubuntu 14.04 LTS Trusty Tahr

### ISSUE THREAD

**Issue by buschtoens** [nodesource/distributions#991]
According to the [`README.md`](https://github.com/nodesource/distributions#debian-and-ubuntu-based-distributions):

> **Supported Ubuntu versions:**
> 
> NodeSource will maintain Ubuntu distributions in active support by Canonical, including LTS and the intermediate releases.
> 
> * **Ubuntu 14.04 LTS** (Trusty Tahr) - **not available for Node.js 10 and later**
> * **Ubuntu 16.04 LTS** (Xenial Xerus)
> * **Ubuntu 18.04 LTS** (Bionic Beaver)
> * **Ubuntu 18.10** (Cosmic Cuttlefish)
> * **Ubuntu 19.04** (Disco Dingo)
> * **Ubuntu 19.10** (Eoan Ermine)

However, a `Release` file for Node 12 on Trusty Tahr exists: https://deb.nodesource.com/node_12.x/dists/trusty/Release

Is this intentional? What is the support status for Node 12 on Trusty Tahr? Will the `Release` file be purged at some point?

**Comment by igsu** [comment]
@buschtoens yes, it was intentional. The same applies for Node 10 and Node 11:

https://deb.nodesource.com/node_10.x/dists/trusty/Release
https://deb.nodesource.com/node_11.x/dists/trusty/Release

The reason is that you can actually use the binaries and even install Node.js 10/12 on Trusty Tahr from our repositories (they are up to date with the last Node available version), but this is not a recommended practice because you may have compatibility issues when using it.

**Comment by buschtoens** [comment]
@igsu Thank you for clarifying this!
